# Generated by Django 5.2.14 on 2026-06-17 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RenameIndex(
            model_name="emailotp",
            new_name="accounts_em_user_id_7388a1_idx",
            old_name="accounts_em_user_id_44618e_idx",
        ),
        migrations.RenameIndex(
            model_name="emailotp",
            new_name="accounts_em_code_518b69_idx",
            old_name="accounts_em_code_819e99_idx",
        ),
    ]
