# Generated by Django 5.2.14 on 2026-06-17 09:10
#
# This migration was adjusted to be safe on existing development/staging
# databases where Django's generated old index names may not exist.
#
# Why:
# Render failed while applying RenameIndex because the expected old index
# accounts_em_user_id_44618e_idx was missing.
#
# Fix:
# - If the old index exists, rename it.
# - If the new index already exists, do nothing.
# - If neither exists, create the expected new index.

from django.db import migrations

RENAME_USER_PURPOSE_USED_INDEX = """
DO $$
BEGIN
    IF to_regclass('accounts_em_user_id_7388a1_idx') IS NULL THEN
        IF to_regclass('accounts_em_user_id_44618e_idx') IS NOT NULL THEN
            ALTER INDEX accounts_em_user_id_44618e_idx
            RENAME TO accounts_em_user_id_7388a1_idx;
        ELSE
            CREATE INDEX accounts_em_user_id_7388a1_idx
            ON accounts_emailotp (user_id, purpose, is_used);
        END IF;
    END IF;
END $$;
"""

REVERSE_USER_PURPOSE_USED_INDEX = """
DO $$
BEGIN
    IF to_regclass('accounts_em_user_id_44618e_idx') IS NULL THEN
        IF to_regclass('accounts_em_user_id_7388a1_idx') IS NOT NULL THEN
            ALTER INDEX accounts_em_user_id_7388a1_idx
            RENAME TO accounts_em_user_id_44618e_idx;
        END IF;
    END IF;
END $$;
"""

RENAME_CODE_INDEX = """
DO $$
BEGIN
    IF to_regclass('accounts_em_code_518b69_idx') IS NULL THEN
        IF to_regclass('accounts_em_code_819e99_idx') IS NOT NULL THEN
            ALTER INDEX accounts_em_code_819e99_idx
            RENAME TO accounts_em_code_518b69_idx;
        ELSE
            CREATE INDEX accounts_em_code_518b69_idx
            ON accounts_emailotp (code);
        END IF;
    END IF;
END $$;
"""

REVERSE_CODE_INDEX = """
DO $$
BEGIN
    IF to_regclass('accounts_em_code_819e99_idx') IS NULL THEN
        IF to_regclass('accounts_em_code_518b69_idx') IS NOT NULL THEN
            ALTER INDEX accounts_em_code_518b69_idx
            RENAME TO accounts_em_code_819e99_idx;
        END IF;
    END IF;
END $$;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=RENAME_USER_PURPOSE_USED_INDEX,
                    reverse_sql=REVERSE_USER_PURPOSE_USED_INDEX,
                ),
                migrations.RunSQL(
                    sql=RENAME_CODE_INDEX,
                    reverse_sql=REVERSE_CODE_INDEX,
                ),
            ],
            state_operations=[
                migrations.RenameIndex(
                    model_name="emailotp",
                    new_name="accounts_em_user_id_7388a1_idx",
                    old_name="accounts_em_user_id_44618e_idx",
                ),
                migrations.RenameIndex(
                    model_name="emailotp",
                    new_name="accounts_em_code_518b69_idx",
                    old_name="accounts_em_code_819e99_idx",
                ),
            ],
        ),
    ]
