# Generated by Django 5.2.14 on 2026-06-17 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interested_in_clubs", models.BooleanField(default=True)),
                ("interested_in_leagues", models.BooleanField(default=True)),
                ("interested_in_unions", models.BooleanField(default=True)),
                ("interested_in_national_teams", models.BooleanField(default=False)),
                ("interested_in_transfers", models.BooleanField(default=False)),
                ("interested_in_highlights", models.BooleanField(default=True)),
                ("interested_in_tickets", models.BooleanField(default=True)),
                ("interested_in_merchandise", models.BooleanField(default=False)),
                (
                    "profile_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS_ONLY", "Followers Only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("show_followed_teams", models.BooleanField(default=True)),
                ("show_attended_matches", models.BooleanField(default=True)),
                (
                    "activity_visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("FOLLOWERS_ONLY", "Followers Only"),
                            ("PRIVATE", "Private"),
                        ],
                        default="FOLLOWERS_ONLY",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interest_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("MATCH_RESULT", "Match Result"),
                            ("UPCOMING_FIXTURE", "Upcoming Fixture"),
                            ("STANDINGS_CHANGE", "Standings Change"),
                            ("NEWS", "News"),
                            ("TICKET_AVAILABLE", "Ticket Available"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "source_content_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. CLUB, LEAGUE, COMPETITION, MATCH",
                        max_length=20,
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("source_name", models.CharField(blank=True, max_length=200)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="accounts_fe_user_id_3b2a73_idx",
                    ),
                    models.Index(
                        fields=["user", "is_read"],
                        name="accounts_fe_user_id_cbecd6_idx",
                    ),
                    models.Index(
                        fields=["user", "item_type"],
                        name="accounts_fe_user_id_187acf_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("UNION", "Union"),
                            ("COMPETITION", "Competition"),
                        ],
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="accounts_fo_content_8d681f_idx",
                    ),
                    models.Index(
                        fields=["user", "content_type"],
                        name="accounts_fo_user_id_826e22_idx",
                    ),
                ],
                "unique_together": {("user", "content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MATCH_REMINDER", "Match Reminder"),
                            ("SCORE_UPDATE", "Score Update"),
                            ("FOLLOWED_TEAM_NEWS", "Followed Team News"),
                            ("STANDINGS_CHANGE", "Standings Change"),
                            ("TICKET_OFFER", "Ticket Offer"),
                            ("GENERAL_NEWS", "General News"),
                        ],
                        max_length=30,
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["event_type"],
                "unique_together": {("user", "event_type")},
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TICKET_PURCHASE", "Ticket Purchase"),
                            ("MEMBERSHIP_FEE", "Membership Fee"),
                            ("MERCHANDISE", "Merchandise"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("REFUND", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "payment histories",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "payment_type"],
                        name="accounts_pa_user_id_802602_idx",
                    ),
                    models.Index(
                        fields=["user", "status"], name="accounts_pa_user_id_ea1b56_idx"
                    ),
                ],
            },
        ),
    ]
