# Generated by Django 5.2.14 on 2026-06-23 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_interest_preferences_and_club_repair"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_role",
                    models.CharField(
                        choices=[
                            ("FAN", "Fan / Member"),
                            ("CLUB_ADMIN", "Club Admin"),
                            ("LEAGUE_ADMIN", "League Admin"),
                            ("UNION_ADMIN", "Union / Federation Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                            ("REFEREE", "Referee / Match Official"),
                            ("TICKETING_OFFICER", "Ticketing Officer"),
                            ("SPONSOR", "Sponsor"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the role change request"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason provided by the reviewer for rejection",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_approval_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="role_approval_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_approval_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role Approval Request",
                "verbose_name_plural": "Role Approval Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="accounts_ro_status_d2f411_idx",
                    ),
                    models.Index(
                        fields=["target_user", "status"],
                        name="accounts_ro_target__0f9ea5_idx",
                    ),
                ],
            },
        ),
    ]
