# Generated by Django 5.2.14 on 2026-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_add_missing_user_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                ],
                default="EMAIL_VERIFICATION",
                max_length=50,
            ),
        ),
    ]
