# Generated by Django 5.2.14 on 2026-06-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_roleapproval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("MATCH_REMINDER", "Match Reminder"),
                    ("SCORE_UPDATE", "Score Update"),
                    ("FOLLOWED_TEAM_NEWS", "Followed Team News"),
                    ("STANDINGS_CHANGE", "Standings Change"),
                    ("TICKET_UPDATES", "Ticket Updates"),
                    ("TICKET_OFFER", "Ticket Offer"),
                    ("MEMBERSHIP_UPDATES", "Membership Updates"),
                    ("SPONSORSHIP_UPDATES", "Sponsorship Updates"),
                    ("FANTASY_UPDATES", "Fantasy Updates"),
                    ("LEAGUE_NEWS", "League News"),
                    ("CLUB_NEWS", "Club News"),
                    ("GENERAL_NEWS", "General News"),
                    ("MARKETING_UPDATES", "Marketing Updates"),
                ],
                max_length=30,
            ),
        ),
    ]
