# Generated by Django 5.2.14 on 2026-06-25 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_notificationpreference_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("MATCH_REMINDER", "Match Reminder"),
                            ("SCORE_UPDATE", "Score Update"),
                            ("FOLLOWED_TEAM_NEWS", "Followed Team News"),
                            ("STANDINGS_CHANGE", "Standings Change"),
                            ("TICKET_UPDATES", "Ticket Updates"),
                            ("TICKET_OFFER", "Ticket Offer"),
                            ("MEMBERSHIP_UPDATES", "Membership Updates"),
                            ("SPONSORSHIP_UPDATES", "Sponsorship Updates"),
                            ("FANTASY_UPDATES", "Fantasy Updates"),
                            ("LEAGUE_NEWS", "League News"),
                            ("CLUB_NEWS", "Club News"),
                            ("GENERAL_NEWS", "General News"),
                            ("MARKETING_UPDATES", "Marketing Updates"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TICKET", "Ticket"),
                            ("PAYMENT", "Payment"),
                            ("MEMBERSHIP", "Membership"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("FANTASY", "Fantasy"),
                            ("MATCH", "Match"),
                            ("CLUB", "Club"),
                            ("SYSTEM", "System"),
                        ],
                        default="SYSTEM",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("HIGH", "High"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField(blank=True)),
                ("action_url", models.CharField(blank=True, max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read", "created_at"],
                        name="accounts_no_user_id_cabb0a_idx",
                    ),
                    models.Index(
                        fields=["user", "category", "created_at"],
                        name="accounts_no_user_id_56141b_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="accounts_no_event_t_69df80_idx"
                    ),
                ],
            },
        ),
    ]
