# Generated by Django 5.2.14 on 2026-07-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_bio_user_date_of_birth_user_favourite_sport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="clubs/banners/"),
        ),
        migrations.AddField(
            model_name="club",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="clubs/logos/"),
        ),
        migrations.AddField(
            model_name="club",
            name="primary_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="club",
            name="secondary_color",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="club",
            name="short_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="club",
            name="sport",
            field=models.CharField(
                choices=[
                    ("RUGBY", "Rugby"),
                    ("FOOTBALL", "Football"),
                    ("BASKETBALL", "Basketball"),
                    ("MULTI_SPORT", "Multi-Sport"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=30,
            ),
        ),
    ]
