# Generated by Django 5.2.14 on 2026-07-14 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_club_banner_club_logo_club_primary_color_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubAdminScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CLUB_ADMIN", "Club Administrator"),
                            ("CHAIRMAN", "Chairman"),
                            ("TREASURER", "Treasurer"),
                            ("TEAM_MANAGER", "Team Manager"),
                            ("TICKETING_OFFICER", "Ticketing Officer"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="CLUB_ADMIN",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.club"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_admin_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["club__name", "user__email"],
                "unique_together": {("user", "club")},
            },
        ),
    ]
