# Generated by Django 5.2.14 on 2026-07-16 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_clubadminscope"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(blank=True, max_length=200)),
                ("pitch_count", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["club__name", "name"],
            },
        ),
        migrations.AlterModelOptions(
            name="feeditem",
            options={"ordering": ["-published_at", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="interestpreference",
            options={"ordering": ["user__email"]},
        ),
        migrations.AlterModelOptions(
            name="notificationpreference",
            options={"ordering": ["user__email"]},
        ),
        migrations.AlterModelOptions(
            name="paymenthistory",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="roleapproval",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="wallet",
            options={"ordering": ["user__email"]},
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_user_id_7388a1_idx",
        ),
        migrations.RemoveIndex(
            model_name="emailotp",
            name="accounts_em_code_518b69_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeditem",
            name="accounts_fe_user_id_3b2a73_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeditem",
            name="accounts_fe_user_id_cbecd6_idx",
        ),
        migrations.RemoveIndex(
            model_name="feeditem",
            name="accounts_fe_user_id_187acf_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="accounts_fo_content_8d681f_idx",
        ),
        migrations.RemoveIndex(
            model_name="follow",
            name="accounts_fo_user_id_826e22_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_user_id_cabb0a_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_user_id_56141b_idx",
        ),
        migrations.RemoveIndex(
            model_name="notification",
            name="accounts_no_event_t_69df80_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymenthistory",
            name="accounts_pa_user_id_802602_idx",
        ),
        migrations.RemoveIndex(
            model_name="paymenthistory",
            name="accounts_pa_user_id_ea1b56_idx",
        ),
        migrations.RemoveIndex(
            model_name="roleapproval",
            name="accounts_ro_status_d2f411_idx",
        ),
        migrations.RemoveIndex(
            model_name="roleapproval",
            name="accounts_ro_target__0f9ea5_idx",
        ),
        migrations.AlterUniqueTogether(
            name="notificationpreference",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="attempts",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="is_used",
        ),
        migrations.RemoveField(
            model_name="emailotp",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="is_read",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="link",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="relevance_score",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="source_content_type",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="source_name",
        ),
        migrations.RemoveField(
            model_name="feeditem",
            name="source_object_id",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="action_url",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="read_at",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="description",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="payment_type",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="paymenthistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="roleapproval",
            name="rejection_reason",
        ),
        migrations.RemoveField(
            model_name="roleapproval",
            name="requested_by",
        ),
        migrations.RemoveField(
            model_name="roleapproval",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="roleapproval",
            name="target_user",
        ),
        migrations.RemoveField(
            model_name="wallet",
            name="is_active",
        ),
        migrations.AddField(
            model_name="feeditem",
            name="content_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="feed/"),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="governance_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="membership_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="sponsorship_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="ticket_updates",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="wallet",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="accounts.wallet",
            ),
        ),
        migrations.AddField(
            model_name="roleapproval",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="roleapproval",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="emailotp",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Email Verification"),
                    ("PASSWORD_RESET", "Password Reset"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="follow",
            name="content_type",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="follow",
            name="object_id",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("MEMBERSHIP", "Membership"),
                    ("TICKETING", "Ticketing"),
                    ("SPONSORSHIP", "Sponsorship"),
                    ("GOVERNANCE", "Governance"),
                    ("CLUB", "Club"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="currency",
            field=models.CharField(default="UGX", max_length=10),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="reference",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(default="PENDING", max_length=30),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="reason",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="requested_role",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="currency",
            field=models.CharField(default="UGX", max_length=10),
        ),
        migrations.AddField(
            model_name="venue",
            name="club",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="venues",
                to="accounts.club",
            ),
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="sms_enabled",
        ),
        migrations.RemoveField(
            model_name="notificationpreference",
            name="updated_at",
        ),
        migrations.AlterUniqueTogether(
            name="venue",
            unique_together={("club", "name")},
        ),
    ]
