# Generated by Django 5.2.14 on 2026-07-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_venue_alter_feeditem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
