# Generated by Django 5.2.14 on 2026-07-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_emailotp_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailotp",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
