# Generated by Django 5.2.14 on 2026-07-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_emailotp_is_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("MEMBERSHIP", "Membership"),
                    ("TICKET_UPDATES", "Ticket Updates"),
                    ("SPONSORSHIP", "Sponsorship"),
                    ("GOVERNANCE", "Governance"),
                    ("CLUB", "Club"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("MEMBERSHIP_FEE", "Membership Fee"),
                    ("TICKET_PURCHASE", "Ticket Purchase"),
                    ("SPONSORSHIP", "Sponsorship"),
                    ("LEGACY", "Legacy Payment"),
                ],
                default="LEGACY",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
    ]
