# Generated by Django 5.2.14 on 2026-07-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_notificationpreference_event_type_and_more"),
    ]

    operations = []
