# Generated by Django 5.2.14 on 2026-07-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_notificationpreference_event_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="sms_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
