# Generated by Django 5.2.14 on 2026-07-17 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_notificationpreference_sms_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("MEMBERSHIP", "Membership"),
                    ("TICKET", "Ticket"),
                    ("TICKETING", "Ticketing"),
                    ("SPONSORSHIP", "Sponsorship"),
                    ("GOVERNANCE", "Governance"),
                    ("CLUB", "Club"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
    ]
