# Generated by Django 5.2.14 on 2026-07-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0016_paymenthistory_description_paymenthistory_metadata_and_more",
        ),
    ]

    # The canonical repair branch supersedes this migration's schema intent.
    # Keep the filename and dependency for migration-recorder compatibility;
    # canonical migrations reconcile databases where the old operations ran.
    operations = []
