# Generated by Django 5.2.14 on 2026-07-18 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0016_paymenthistory_description_paymenthistory_metadata_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="event_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="notification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("normal", "Normal"), ("high", "High")],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="wallet",
            name="balance_note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="wallet",
            name="stored_balance_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="notificationpreference",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("SYSTEM", "System"),
                    ("MEMBERSHIP", "Membership"),
                    ("TICKET_UPDATES", "Ticket Updates"),
                    ("SPONSORSHIP", "Sponsorship"),
                    ("GOVERNANCE", "Governance"),
                    ("CLUB", "Club"),
                    ("ACCOUNT_SECURITY", "Account Security"),
                    ("PAYMENT", "Payment"),
                    ("MARKETING_UPDATES", "Marketing Updates"),
                ],
                default="SYSTEM",
                max_length=30,
            ),
        ),
    ]
