# Generated by Django 5.2.14 on 2026-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_notification_action_url_notification_event_type_and_more"),
    ]

    # The canonical repair branch supersedes this migration's schema intent.
    # Keep the filename and dependency for migration-recorder compatibility;
    # canonical migrations reconcile databases where the old operations ran.
    operations = []
