# Generated by Django 5.2.14 on 2026-07-18 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_notification_read_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "event_type"), name="unique_user_event_type"
            ),
        ),
    ]
