# Generated by Django 5.2.14 on 2026-07-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_add_notification_read_at"),
    ]

    # The canonical repair branch supersedes this migration's schema intent.
    # Keep the filename and dependency for migration-recorder compatibility;
    # canonical migrations reconcile databases where the old operations ran.
    operations = []
