# Generated by Django 5.2.14 on 2026-07-17 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0019_finalize_notification_contracts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feeditem",
            options={"ordering": ["-relevance_score", "-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="roleapproval",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Role Approval Request",
                "verbose_name_plural": "Role Approval Requests",
            },
        ),
        migrations.RenameField(
            model_name="roleapproval",
            old_name="approved_by",
            new_name="reviewed_by",
        ),
        migrations.RenameField(
            model_name="roleapproval",
            old_name="user",
            new_name="target_user",
        ),
        migrations.AddField(
            model_name="feeditem",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="item_type",
            field=models.CharField(
                choices=[
                    ("MATCH_RESULT", "Match Result"),
                    ("UPCOMING_FIXTURE", "Upcoming Fixture"),
                    ("STANDINGS_CHANGE", "Standings Change"),
                    ("NEWS", "News"),
                    ("TICKET_AVAILABLE", "Ticket Available"),
                ],
                default="NEWS",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="link",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="relevance_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="source_content_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="source_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="feeditem",
            name="source_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="roleapproval",
            name="rejection_reason",
            field=models.TextField(
                blank=True, help_text="Reason provided by the reviewer for rejection"
            ),
        ),
        migrations.AddField(
            model_name="roleapproval",
            name="requested_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_approval_requests_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="feeditem",
            name="title",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="follow",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("CLUB", "Club"),
                    ("LEAGUE", "League"),
                    ("UNION", "Union"),
                    ("COMPETITION", "Competition"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="reason",
            field=models.TextField(
                blank=True, help_text="Reason for the role change request"
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="requested_role",
            field=models.CharField(
                choices=[
                    ("FAN", "Fan / Member"),
                    ("CLUB_ADMIN", "Club Admin"),
                    ("LEAGUE_ADMIN", "League Admin"),
                    ("UNION_ADMIN", "Union / Federation Admin"),
                    ("SUPER_ADMIN", "Super Admin"),
                    ("REFEREE", "Referee / Match Official"),
                    ("TICKETING_OFFICER", "Ticketing Officer"),
                    ("SPONSOR", "Sponsor"),
                ],
                default="FAN",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_approval_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="roleapproval",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_approval_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(
                fields=["user", "-created_at"], name="accounts_fe_user_id_3b2a73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(
                fields=["user", "is_read"], name="accounts_fe_user_id_cbecd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feeditem",
            index=models.Index(
                fields=["user", "item_type"], name="accounts_fe_user_id_187acf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="accounts_fo_content_8d681f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(
                fields=["user", "content_type"], name="accounts_fo_user_id_826e22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleapproval",
            index=models.Index(
                fields=["status", "-created_at"], name="accounts_ro_status_d2f411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roleapproval",
            index=models.Index(
                fields=["target_user", "status"], name="accounts_ro_target__0f9ea5_idx"
            ),
        ),
    ]
