"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import sys
from pathlib import Path
from datetime import timedelta

try:
    import dj_database_url
except ImportError:
    dj_database_url = None
from decouple import Csv, config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "DJANGO_SECRET_KEY",
    default="django-insecure-dev-key-at-least-32-characters-long-for-signing",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DJANGO_DEBUG", default=True, cast=bool)

ALLOWED_HOSTS = config(
    "DJANGO_ALLOWED_HOSTS",
    default="localhost,127.0.0.1,0.0.0.0",
    cast=Csv(),
)

# Render health checks and proxy headers
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "channels",
    "storages",
    # Local apps
    "accounts",
    "dashboards",
    "governance",
    "teams",
    "sponsorships",
    "ticketing",
    "memberships",
    "fantasy",
    "engagements",
    "monitoring",
    "platform_admin",
    "rbac.apps.RbacConfig",
    "analytics.apps.AnalyticsConfig",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config("DATABASE_URL", default=None)

if DATABASE_URL and dj_database_url:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=True,
        ),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config("DB_NAME", default="league_os"),
            "USER": config("DB_USER", default="league_os_user"),
            "PASSWORD": config("DB_PASSWORD", default="league_os_password"),
            "HOST": config("DB_HOST", default="db"),
            "PORT": config("DB_PORT", default="5432"),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "accounts.validators.AdvancedStrengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Kampala"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

USE_S3_MEDIA = config("USE_S3_MEDIA", default=False, cast=bool)
PRIVATE_MEDIA_URL_EXPIRY = config(
    "S3_PRIVATE_URL_EXPIRY",
    default=900,
    cast=int,
)

if PRIVATE_MEDIA_URL_EXPIRY <= 0:
    raise ImproperlyConfigured("S3_PRIVATE_URL_EXPIRY must be greater than zero.")

if USE_S3_MEDIA:
    S3_ACCESS_KEY_ID = config(
        "S3_ACCESS_KEY_ID",
        default=config("AWS_ACCESS_KEY_ID", default=""),
    )
    S3_SECRET_ACCESS_KEY = config(
        "S3_SECRET_ACCESS_KEY",
        default=config("AWS_SECRET_ACCESS_KEY", default=""),
    )

    if not S3_ACCESS_KEY_ID or not S3_SECRET_ACCESS_KEY:
        raise ImproperlyConfigured(
            "S3 media is enabled but storage credentials are missing."
        )

    S3_PUBLIC_BUCKET_NAME = config(
        "S3_PUBLIC_BUCKET_NAME",
        default=config(
            "AWS_STORAGE_BUCKET_NAME",
            default="league-os-public",
        ),
    )
    S3_PRIVATE_BUCKET_NAME = config(
        "S3_PRIVATE_BUCKET_NAME",
        default="league-os-private",
    )
    S3_REGION_NAME = config(
        "S3_REGION_NAME",
        default=config("AWS_S3_REGION_NAME", default="us-east-1"),
    )
    S3_ENDPOINT_URL = config(
        "S3_ENDPOINT_URL",
        default=config(
            "AWS_S3_ENDPOINT_URL",
            default=f"https://{S3_REGION_NAME}.digitaloceanspaces.com",
        ),
    ).rstrip("/")
    S3_ADDRESSING_STYLE = config(
        "S3_ADDRESSING_STYLE",
        default="path",
    )
    S3_PUBLIC_CUSTOM_DOMAIN = config(
        "S3_PUBLIC_CUSTOM_DOMAIN",
        default=config("AWS_S3_CUSTOM_DOMAIN", default=""),
    ).strip()
    S3_PUBLIC_URL_PROTOCOL = config(
        "S3_PUBLIC_URL_PROTOCOL",
        default="https:",
    ).strip()
    S3_PUBLIC_CACHE_CONTROL = config(
        "S3_PUBLIC_CACHE_CONTROL",
        default="public, max-age=86400",
    )
    S3_PRIVATE_EXTERNAL_BASE_URL = (
        config(
            "S3_PRIVATE_EXTERNAL_BASE_URL",
            default="",
        )
        .strip()
        .rstrip("/")
    )

    if not S3_PUBLIC_URL_PROTOCOL.endswith(":"):
        S3_PUBLIC_URL_PROTOCOL = f"{S3_PUBLIC_URL_PROTOCOL}:"

    common_s3_options = {
        "access_key": S3_ACCESS_KEY_ID,
        "secret_key": S3_SECRET_ACCESS_KEY,
        "region_name": S3_REGION_NAME,
        "endpoint_url": S3_ENDPOINT_URL,
        "addressing_style": S3_ADDRESSING_STYLE,
        "signature_version": "s3v4",
        "file_overwrite": False,
    }

    public_s3_options = {
        **common_s3_options,
        "bucket_name": S3_PUBLIC_BUCKET_NAME,
        "default_acl": "public-read",
        "querystring_auth": False,
        "object_parameters": {
            "CacheControl": S3_PUBLIC_CACHE_CONTROL,
        },
    }

    if S3_PUBLIC_CUSTOM_DOMAIN:
        public_s3_options.update(
            {
                "custom_domain": S3_PUBLIC_CUSTOM_DOMAIN,
                "url_protocol": S3_PUBLIC_URL_PROTOCOL,
            }
        )

    private_s3_options = {
        **common_s3_options,
        "bucket_name": S3_PRIVATE_BUCKET_NAME,
        "default_acl": "private",
        "querystring_auth": True,
        "querystring_expire": PRIVATE_MEDIA_URL_EXPIRY,
        "object_parameters": {
            "CacheControl": "private, no-store",
        },
    }

    STORAGES = {
        "default": {
            "BACKEND": "config.storage_backends.PublicMediaStorage",
            "OPTIONS": public_s3_options,
        },
        "private": {
            "BACKEND": "config.storage_backends.PrivateMediaStorage",
            "OPTIONS": private_s3_options,
        },
        "staticfiles": {
            "BACKEND": ("django.contrib.staticfiles.storage.StaticFilesStorage"),
        },
    }

    if S3_PUBLIC_CUSTOM_DOMAIN:
        MEDIA_URL = (
            f"{S3_PUBLIC_URL_PROTOCOL}//" f"{S3_PUBLIC_CUSTOM_DOMAIN.rstrip('/')}/"
        )
    else:
        MEDIA_URL = f"{S3_ENDPOINT_URL}/" f"{S3_PUBLIC_BUCKET_NAME}/"
else:
    MEDIA_URL = "/media/"
    MEDIA_ROOT = BASE_DIR / "media"

    PRIVATE_MEDIA_URL = "/private-media/"
    PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": MEDIA_ROOT,
                "base_url": MEDIA_URL,
            },
        },
        "private": {
            "BACKEND": ("config.storage_backends.LocalPrivateMediaStorage"),
            "OPTIONS": {
                "location": PRIVATE_MEDIA_ROOT,
                "base_url": PRIVATE_MEDIA_URL,
            },
        },
        "staticfiles": {
            "BACKEND": ("django.contrib.staticfiles.storage.StaticFilesStorage"),
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Django REST Framework
REST_FRAMEWORK = {
    # Membership exports use ?format=csv and ?format=pdf.
    # Disable DRF's renderer query-parameter override so those
    # values reach the export view instead of producing a 404.
    "URL_FORMAT_OVERRIDE": None,
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.FormParser",
        "rest_framework.parsers.MultiPartParser",
    ],
}


# OpenAPI / Swagger documentation
SPECTACULAR_SETTINGS = {
    "TITLE": "League OS Backend API",
    "DESCRIPTION": (
        "API documentation for League OS, a multi-role sports engagement "
        "platform for fans, clubs, leagues, unions, sponsors, ticketing, "
        "governance, dashboards, and membership workflows."
    ),
    "VERSION": "sprint-1-foundation",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
}

# JWT Authentication

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# CORS / CSRF
CORS_ALLOWED_ORIGINS = config(
    "CORS_ALLOWED_ORIGINS",
    default="http://localhost:5173",
    cast=Csv(),
)

CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://localhost:5173",
    cast=Csv(),
)

SESSION_COOKIE_SECURE = config(
    "SESSION_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)

CSRF_COOKIE_SECURE = config(
    "CSRF_COOKIE_SECURE",
    default=not DEBUG,
    cast=bool,
)

# Email / OTP Development Settings
EMAIL_BACKEND = config(
    "EMAIL_BACKEND",
    default="django.core.mail.backends.console.EmailBackend",
)

EMAIL_HOST = config("EMAIL_HOST", default="")
EMAIL_PORT = config("EMAIL_PORT", default=587, cast=int)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=True, cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=False, cast=bool)
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=20, cast=int)

DEFAULT_FROM_EMAIL = config(
    "DEFAULT_FROM_EMAIL",
    default="League OS <noreply@leagueos.local>",
)
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)


OTP_EXPIRY_MINUTES = config("OTP_EXPIRY_MINUTES", default=10, cast=int)

OTP_MAX_ATTEMPTS = config("OTP_MAX_ATTEMPTS", default=5, cast=int)

RUNNING_TESTS = "test" in sys.argv

SEND_OTP_EMAILS = config(
    "SEND_OTP_EMAILS",
    default=(not DEBUG and not RUNNING_TESTS),
    cast=bool,
)

PRINT_DEV_OTPS = config("PRINT_DEV_OTPS", default=False, cast=bool)

# Custom User Model
AUTH_USER_MODEL = "accounts.User"

# Google OAuth2 Settings
# ---------------------------------------------------------------------------

GOOGLE_OAUTH2_CLIENT_ID = config("GOOGLE_OAUTH2_CLIENT_ID", default="")
GOOGLE_OAUTH2_CLIENT_SECRET = config("GOOGLE_OAUTH2_CLIENT_SECRET", default="")

# Flutterwave Payment Settings
# In development, use Flutterwave TEST keys.
# In production, the client must provide LIVE keys from their own Flutterwave account.

FLUTTERWAVE_MODE = config("FLUTTERWAVE_MODE", default="test")

FLUTTERWAVE_BASE_URL = config(
    "FLUTTERWAVE_BASE_URL",
    default="https://api.flutterwave.com/v3",
)

FLUTTERWAVE_PUBLIC_KEY = config("FLUTTERWAVE_PUBLIC_KEY", default="")
FLUTTERWAVE_SECRET_KEY = config("FLUTTERWAVE_SECRET_KEY", default="")
FLUTTERWAVE_SECRET_HASH = config("FLUTTERWAVE_SECRET_HASH", default="")

FLUTTERWAVE_REDIRECT_URL = config(
    "FLUTTERWAVE_REDIRECT_URL",
    default="http://localhost:5173/sponsor/payment/processing",
)

# Sponsorship Payment
FLUTTERWAVE_PAYMENT_TITLE = config(
    "FLUTTERWAVE_PAYMENT_TITLE",
    default="League OS Sponsorship Payment",
)

FLUTTERWAVE_TICKET_PAYMENT_TITLE = config(
    "FLUTTERWAVE_TICKET_PAYMENT_TITLE",
    default="League OS Match Ticket Payment",
)

# Ticket Payment
FLUTTERWAVE_TICKET_REDIRECT_URL = config(
    "FLUTTERWAVE_TICKET_REDIRECT_URL",
    default="http://localhost:8000/api/ticketing/flutterwave/verify/",
)

FLUTTERWAVE_MEMBERSHIP_PAYMENT_TITLE = config(
    "FLUTTERWAVE_MEMBERSHIP_PAYMENT_TITLE",
    default="League OS Membership Payment",
)

FLUTTERWAVE_MEMBERSHIP_REDIRECT_URL = config(
    "FLUTTERWAVE_MEMBERSHIP_REDIRECT_URL",
    default="http://localhost:8000/api/memberships/flutterwave/verify/",
)

FLUTTERWAVE_PAYMENT_LOGO_URL = config(
    "FLUTTERWAVE_PAYMENT_LOGO_URL",
    default="",
)

FLUTTERWAVE_TIMEOUT_SECONDS = config(
    "FLUTTERWAVE_TIMEOUT_SECONDS",
    default=30,
    cast=int,
)

TICKETING_DEMO_CHECKOUT_ENABLED = config(
    "TICKETING_DEMO_CHECKOUT_ENABLED",
    default=False,
    cast=bool,
)

TICKET_RESERVATION_MINUTES = config(
    "TICKET_RESERVATION_MINUTES",
    default=10,
    cast=int,
)

# Channels / WebSocket configuration
# ---------------------------------------------------------------------------

ASGI_APPLICATION = "config.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

MEMBERSHIP_DEMO_CHECKOUT_ENABLED = config(
    "MEMBERSHIP_DEMO_CHECKOUT_ENABLED",
    default=False,
    cast=bool,
)
