from django.urls import path
from . import (
    admin_workspace_views,
    official_appointment_views,
    union_management_views,
    views,
)

urlpatterns = [
    # Authenticated role dashboards
    path("me/", views.my_dashboard_view, name="my-dashboard"),
    path("fan/", views.fan_dashboard_view, name="fan-dashboard"),
    path("club-admin/", views.club_admin_dashboard_view, name="club-admin-dashboard"),
    path(
        "club-admin/role/",
        views.club_admin_role_detection_view,
        name="club-admin-role-detection",
    ),
    path(
        "club-admin/menu-items/",
        views.club_admin_menu_items_view,
        name="club-admin-menu-items",
    ),
    path(
        "club-admin/workspace-context/",
        views.club_admin_workspace_context_view,
        name="club-admin-workspace-context",
    ),
    path(
        "league-admin/",
        views.league_admin_dashboard_view,
        name="league-admin-dashboard",
    ),
    path(
        "league-admin/workspace/",
        admin_workspace_views.league_admin_workspace_view,
        name="league-admin-workspace",
    ),
    path(
        "club-admin/workspace/",
        admin_workspace_views.club_admin_workspace_view,
        name="club-admin-workspace",
    ),
    path(
        "ticketing-officer/workspace/",
        admin_workspace_views.ticketing_officer_workspace_view,
        name="ticketing-officer-workspace",
    ),
    path(
        "union-admin/", views.union_admin_dashboard_view, name="union-admin-dashboard"
    ),
    path(
        "union-admin/workspaces/",
        views.union_admin_workspaces_me_view,
        name="union-admin-workspaces-me",
    ),
    path(
        "union-admin/switch-workspace/",
        views.union_admin_switch_workspace_view,
        name="union-admin-switch-workspace",
    ),
    path(
        "union-admin/workspace/",
        views.union_admin_workspace_dashboard_view,
        name="union-admin-workspace-dashboard",
    ),
    path(
        "union-admin/operations/",
        views.union_admin_operations_dashboard_view,
        name="union-admin-operations-dashboard",
    ),
    path(
        "union-admin/workspace-users/",
        views.union_admin_workspace_users_view,
        name="union-admin-workspace-users",
    ),
    path(
        "union-admin/finance/",
        views.union_admin_finance_dashboard_view,
        name="union-admin-finance-dashboard",
    ),
    path(
        "union-admin/transfer-owner/",
        views.union_admin_transfer_owner_view,
        name="union-admin-transfer-owner",
    ),
    path(
        "union-admin/clubs/",
        union_management_views.union_admin_clubs_view,
        name="union-admin-clubs",
    ),
    path(
        "union-admin/clubs/<int:club_id>/",
        union_management_views.union_admin_club_detail_view,
        name="union-admin-club-detail",
    ),
    path(
        "union-admin/leagues/",
        union_management_views.union_admin_leagues_view,
        name="union-admin-leagues",
    ),
    path(
        "union-admin/seasons/",
        union_management_views.union_admin_seasons_view,
        name="union-admin-seasons",
    ),
    path(
        "union-admin/competitions/",
        union_management_views.union_admin_competitions_view,
        name="union-admin-competitions-manage",
    ),
    path(
        "union-admin/league-clubs/bulk-add/",
        union_management_views.union_admin_league_clubs_bulk_add_view,
        name="union-admin-league-clubs-bulk-add",
    ),
    path(
        "union-admin/league-clubs/",
        union_management_views.union_admin_league_clubs_view,
        name="union-admin-league-clubs",
    ),
    path(
        "union-admin/league-clubs/<int:membership_id>/",
        union_management_views.union_admin_league_club_detail_view,
        name="union-admin-league-club-detail",
    ),
    path(
        "union-admin/promote-relegate/",
        union_management_views.union_admin_promote_relegate_view,
        name="union-admin-promote-relegate",
    ),
    path(
        "union-admin/national-teams/",
        union_management_views.union_admin_national_teams_view,
        name="union-admin-national-teams",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/",
        union_management_views.union_admin_national_team_detail_view,
        name="union-admin-national-team-detail",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/members/",
        union_management_views.union_admin_national_team_members_view,
        name="union-admin-national-team-members",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/members/<int:member_id>/",
        union_management_views.union_admin_national_team_member_detail_view,
        name="union-admin-national-team-member-detail",
    ),
    path(
        "union-admin/registration-applications/",
        union_management_views.union_admin_registration_applications_view,
        name="union-admin-registration-applications",
    ),
    path(
        "union-admin/registration-applications/<int:application_id>/",
        union_management_views.union_admin_registration_application_detail_view,
        name="union-admin-registration-application-detail",
    ),
    path(
        "union-admin/official-readiness/",
        union_management_views.union_admin_official_readiness_view,
        name="union-admin-official-readiness",
    ),
    path(
        "union-admin/referees/",
        union_management_views.union_admin_match_officials_view,
        name="union-admin-match-officials",
    ),
    path(
        "union-admin/referees/<int:official_id>/",
        union_management_views.union_admin_match_official_detail_view,
        name="union-admin-match-official-detail",
    ),
    path(
        "union-admin/fixture-official-appointments/",
        union_management_views.union_admin_fixture_official_appointments_view,
        name="union-admin-fixture-official-appointments",
    ),
    path(
        "union-admin/fixture-official-appointments/<int:assignment_id>/",
        union_management_views.union_admin_fixture_official_appointment_detail_view,
        name="union-admin-fixture-official-appointment-detail",
    ),
    path(
        "union-admin/league-admin-scopes/",
        official_appointment_views.union_admin_league_admin_scopes_view,
        name="union-admin-league-admin-scopes",
    ),
    path(
        "union-admin/league-admin-scopes/<int:scope_id>/",
        official_appointment_views.union_admin_league_admin_scope_detail_view,
        name="union-admin-league-admin-scope-detail",
    ),
    # League/competition-scoped match official operations
    path(
        "league-admin/scopes/",
        official_appointment_views.league_admin_scopes_view,
        name="league-admin-scopes",
    ),
    path(
        "league-admin/fixtures/",
        official_appointment_views.league_admin_fixtures_view,
        name="league-admin-fixtures",
    ),
    path(
        "league-admin/match-officials/",
        official_appointment_views.league_admin_match_officials_view,
        name="league-admin-match-officials",
    ),
    path(
        "league-admin/fixture-official-appointments/",
        official_appointment_views.league_admin_appointments_view,
        name="league-admin-fixture-official-appointments",
    ),
    path(
        "league-admin/fixture-official-appointments/<int:assignment_id>/",
        official_appointment_views.league_admin_appointment_detail_view,
        name="league-admin-fixture-official-appointment-detail",
    ),
    # Match official self-service
    path(
        "match-official/appointments/",
        official_appointment_views.match_official_appointments_view,
        name="match-official-appointments",
    ),
    path(
        "match-official/appointments/<int:assignment_id>/response/",
        official_appointment_views.match_official_appointment_response_view,
        name="match-official-appointment-response",
    ),
    path(
        "union-admin/fixtures/<int:match_id>/reschedule/",
        union_management_views.union_admin_fixture_reschedule_view,
        name="union-admin-fixture-reschedule",
    ),
    path(
        "union-admin/generate-fixtures/",
        union_management_views.union_admin_generate_fixtures_view,
        name="union-admin-generate-fixtures",
    ),
    path(
        "super-admin/", views.super_admin_dashboard_view, name="super-admin-dashboard"
    ),
    path("referee/", views.referee_dashboard_view, name="referee-dashboard"),
    path(
        "ticketing-officer/",
        views.ticketing_officer_dashboard_view,
        name="ticketing-officer-dashboard",
    ),
    path("sponsor/", views.sponsor_dashboard_view, name="sponsor-dashboard"),
    # Public / No-auth endpoints (AllowAny)
    path(
        "public/fixtures/",
        views.public_fixtures_view,
        name="public-fixtures",
    ),
    path(
        "public/results/",
        views.public_results_view,
        name="public-results",
    ),
    path(
        "public/standings/",
        views.public_standings_view,
        name="public-standings",
    ),
    path(
        "public/clubs/",
        views.public_clubs_view,
        name="public-clubs",
    ),
    path(
        "public/unions/",
        views.public_unions_view,
        name="public-unions",
    ),
    path(
        "public/leagues/",
        views.public_leagues_view,
        name="public-leagues",
    ),
    path(
        "public/competitions/",
        views.public_competitions_view,
        name="public-competitions",
    ),
    # Match detail endpoint
    path(
        "public/matches/<int:match_id>/",
        views.public_match_detail_view,
        name="public-match-detail",
    ),
    # Standings calculation / recomputation endpoint
    path(
        "public/standings/calculate/",
        views.public_standings_calculation_view,
        name="public-standings-calculate",
    ),
]
