from django.urls import path
from . import views, union_management_views

urlpatterns = [
    # Authenticated role dashboards
    path("me/", views.my_dashboard_view, name="my-dashboard"),
    path("fan/", views.fan_dashboard_view, name="fan-dashboard"),
    path("club-admin/", views.club_admin_dashboard_view, name="club-admin-dashboard"),
    path(
        "league-admin/",
        views.league_admin_dashboard_view,
        name="league-admin-dashboard",
    ),
    path(
        "union-admin/", views.union_admin_dashboard_view, name="union-admin-dashboard"
    ),
    path(
        "union-admin/workspaces/",
        views.union_admin_workspaces_me_view,
        name="union-admin-workspaces-me",
    ),
    path(
        "union-admin/switch-workspace/",
        views.union_admin_switch_workspace_view,
        name="union-admin-switch-workspace",
    ),
    path(
        "union-admin/workspace/",
        views.union_admin_workspace_dashboard_view,
        name="union-admin-workspace-dashboard",
    ),
    path(
        "union-admin/operations/",
        views.union_admin_operations_dashboard_view,
        name="union-admin-operations-dashboard",
    ),
    path(
        "union-admin/workspace-users/",
        views.union_admin_workspace_users_view,
        name="union-admin-workspace-users",
    ),
    path(
        "union-admin/finance/",
        views.union_admin_finance_dashboard_view,
        name="union-admin-finance-dashboard",
    ),
    path(
        "union-admin/transfer-owner/",
        views.union_admin_transfer_owner_view,
        name="union-admin-transfer-owner",
    ),
    path(
        "union-admin/clubs/",
        union_management_views.union_admin_clubs_view,
        name="union-admin-clubs",
    ),
    path(
        "union-admin/clubs/<int:club_id>/",
        union_management_views.union_admin_club_detail_view,
        name="union-admin-club-detail",
    ),
    path(
        "union-admin/leagues/",
        union_management_views.union_admin_leagues_view,
        name="union-admin-leagues",
    ),
    path(
        "union-admin/seasons/",
        union_management_views.union_admin_seasons_view,
        name="union-admin-seasons",
    ),
    path(
        "union-admin/competitions/",
        union_management_views.union_admin_competitions_view,
        name="union-admin-competitions-manage",
    ),
    path(
        "union-admin/league-clubs/bulk-add/",
        union_management_views.union_admin_league_clubs_bulk_add_view,
        name="union-admin-league-clubs-bulk-add",
    ),
    path(
        "union-admin/league-clubs/",
        union_management_views.union_admin_league_clubs_view,
        name="union-admin-league-clubs",
    ),
    path(
        "union-admin/league-clubs/<int:membership_id>/",
        union_management_views.union_admin_league_club_detail_view,
        name="union-admin-league-club-detail",
    ),
    path(
        "union-admin/promote-relegate/",
        union_management_views.union_admin_promote_relegate_view,
        name="union-admin-promote-relegate",
    ),
    path(
        "union-admin/fixtures/<int:match_id>/reschedule/",
        union_management_views.union_admin_fixture_reschedule_view,
        name="union-admin-fixture-reschedule",
    ),
    path(
        "union-admin/generate-fixtures/",
        union_management_views.union_admin_generate_fixtures_view,
        name="union-admin-generate-fixtures",
    ),
    path(
        "super-admin/", views.super_admin_dashboard_view, name="super-admin-dashboard"
    ),
    path("referee/", views.referee_dashboard_view, name="referee-dashboard"),
    path(
        "ticketing-officer/",
        views.ticketing_officer_dashboard_view,
        name="ticketing-officer-dashboard",
    ),
    path("sponsor/", views.sponsor_dashboard_view, name="sponsor-dashboard"),
    # Public / No-auth endpoints (AllowAny)
    path(
        "public/fixtures/",
        views.public_fixtures_view,
        name="public-fixtures",
    ),
    path(
        "public/results/",
        views.public_results_view,
        name="public-results",
    ),
    path(
        "public/standings/",
        views.public_standings_view,
        name="public-standings",
    ),
    path(
        "public/clubs/",
        views.public_clubs_view,
        name="public-clubs",
    ),
    path(
        "public/unions/",
        views.public_unions_view,
        name="public-unions",
    ),
    path(
        "public/leagues/",
        views.public_leagues_view,
        name="public-leagues",
    ),
    path(
        "public/competitions/",
        views.public_competitions_view,
        name="public-competitions",
    ),
    # Match detail endpoint
    path(
        "public/matches/<int:match_id>/",
        views.public_match_detail_view,
        name="public-match-detail",
    ),
    # Standings calculation / recomputation endpoint
    path(
        "public/standings/calculate/",
        views.public_standings_calculation_view,
        name="public-standings-calculate",
    ),
]
