from django.urls import path
from . import (
    admin_workspace_views,
    official_appointment_views,
    union_competition_views,
    union_club_views,
    union_governance_views,
    union_league_views,
    union_management_views,
    union_player_eligibility_views,
    union_player_review_views,
    union_player_transfer_views,
    views,
)

urlpatterns = [
    # Authenticated role dashboards
    path("me/", views.my_dashboard_view, name="my-dashboard"),
    path("fan/", views.fan_dashboard_view, name="fan-dashboard"),
    path("club-admin/", views.club_admin_dashboard_view, name="club-admin-dashboard"),
    path(
        "club-admin/role/",
        views.club_admin_role_detection_view,
        name="club-admin-role-detection",
    ),
    path(
        "club-admin/menu-items/",
        views.club_admin_menu_items_view,
        name="club-admin-menu-items",
    ),
    path(
        "club-admin/workspace-context/",
        views.club_admin_workspace_context_view,
        name="club-admin-workspace-context",
    ),
    path(
        "league-admin/",
        views.league_admin_dashboard_view,
        name="league-admin-dashboard",
    ),
    path(
        "league-admin/workspace/",
        admin_workspace_views.league_admin_workspace_view,
        name="league-admin-workspace",
    ),
    path(
        "club-admin/workspace/",
        admin_workspace_views.club_admin_workspace_view,
        name="club-admin-workspace",
    ),
    path(
        "ticketing-officer/workspace/",
        admin_workspace_views.ticketing_officer_workspace_view,
        name="ticketing-officer-workspace",
    ),
    path(
        "union-admin/", views.union_admin_dashboard_view, name="union-admin-dashboard"
    ),
    path(
        "union-admin/workspaces/",
        views.union_admin_workspaces_me_view,
        name="union-admin-workspaces-me",
    ),
    path(
        "union-admin/switch-workspace/",
        views.union_admin_switch_workspace_view,
        name="union-admin-switch-workspace",
    ),
    path(
        "union-admin/workspace/",
        views.union_admin_workspace_dashboard_view,
        name="union-admin-workspace-dashboard",
    ),
    path(
        "union-admin/operations/",
        views.union_admin_operations_dashboard_view,
        name="union-admin-operations-dashboard",
    ),
    path(
        "union-admin/workspace-users/",
        views.union_admin_workspace_users_view,
        name="union-admin-workspace-users",
    ),
    path(
        "union-admin/finance/",
        views.union_admin_finance_dashboard_view,
        name="union-admin-finance-dashboard",
    ),
    path(
        "union-admin/transfer-owner/",
        views.union_admin_transfer_owner_view,
        name="union-admin-transfer-owner",
    ),
    path(
        "union-admin/approvals/",
        union_governance_views.union_admin_approvals_view,
        name="union-admin-approvals",
    ),
    path(
        "union-admin/approvals/<int:approval_id>/",
        union_governance_views.union_admin_approval_detail_view,
        name="union-admin-approval-detail",
    ),
    path(
        "union-admin/audit-events/",
        union_governance_views.union_admin_audit_events_view,
        name="union-admin-audit-events",
    ),
    path(
        "union-admin/review-comments/",
        union_governance_views.union_admin_review_comments_view,
        name="union-admin-review-comments",
    ),
    path(
        "union-admin/documents/",
        union_governance_views.union_admin_document_references_view,
        name="union-admin-document-references",
    ),
    path(
        "union-admin/clubs/",
        union_club_views.union_admin_clubs_view,
        name="union-admin-clubs",
    ),
    path(
        "union-admin/clubs/<int:club_id>/",
        union_club_views.union_admin_club_detail_view,
        name="union-admin-club-detail",
    ),
    path(
        "union-admin/clubs/<int:club_id>/administrators/",
        union_club_views.union_admin_club_administrators_view,
        name="union-admin-club-administrators",
    ),
    path(
        "union-admin/clubs/<int:club_id>/administrators/<int:scope_id>/",
        union_club_views.union_admin_club_administrator_detail_view,
        name="union-admin-club-administrator-detail",
    ),
    path(
        "union-admin/governance-options/",
        union_league_views.union_admin_governance_options_view,
        name="union-admin-governance-options",
    ),
    path(
        "union-admin/leagues/",
        union_league_views.union_admin_leagues_view,
        name="union-admin-leagues",
    ),
    path(
        "union-admin/leagues/<int:league_id>/",
        union_league_views.union_admin_league_detail_view,
        name="union-admin-league-detail",
    ),
    path(
        "union-admin/leagues/<int:league_id>/administrators/",
        union_league_views.union_admin_league_administrators_view,
        name="union-admin-league-administrators",
    ),
    path(
        "union-admin/leagues/<int:league_id>/administrators/<int:scope_id>/",
        union_league_views.union_admin_league_administrator_detail_view,
        name="union-admin-league-administrator-detail",
    ),
    path(
        "union-admin/seasons/",
        union_management_views.union_admin_seasons_view,
        name="union-admin-seasons",
    ),
    path(
        "union-admin/competitions/",
        union_management_views.union_admin_competitions_view,
        name="union-admin-competitions-manage",
    ),
    path(
        "union-admin/competition-identities/",
        union_competition_views.union_admin_competition_identities_view,
        name="union-admin-competition-identities",
    ),
    path(
        "union-admin/competition-create/",
        union_competition_views.union_admin_competition_create_view,
        name="union-admin-competition-create",
    ),
    path(
        "union-admin/competition-administrators/eligible/",
        union_competition_views.union_admin_competition_eligible_administrators_view,
        name="union-admin-competition-administrators-eligible",
    ),
    path(
        "union-admin/competitions/<int:competition_id>/administrators/",
        union_competition_views.union_admin_competition_administrators_view,
        name="union-admin-competition-administrators",
    ),
    path(
        "union-admin/competitions/<int:competition_id>/administrators/<int:scope_id>/",
        union_competition_views.union_admin_competition_administrator_detail_view,
        name="union-admin-competition-administrator-detail",
    ),
    path(
        "union-admin/competition-identities/<int:identity_id>/editions/",
        union_competition_views.union_admin_competition_editions_view,
        name="union-admin-competition-editions",
    ),
    path(
        "union-admin/competition-editions/<int:edition_id>/transition/",
        union_competition_views.union_admin_competition_edition_transition_view,
        name="union-admin-competition-edition-transition",
    ),
    path(
        "union-admin/league-clubs/bulk-add/",
        union_management_views.union_admin_league_clubs_bulk_add_view,
        name="union-admin-league-clubs-bulk-add",
    ),
    path(
        "union-admin/league-clubs/",
        union_management_views.union_admin_league_clubs_view,
        name="union-admin-league-clubs",
    ),
    path(
        "union-admin/league-clubs/<int:membership_id>/",
        union_management_views.union_admin_league_club_detail_view,
        name="union-admin-league-club-detail",
    ),
    path(
        "union-admin/promote-relegate/",
        union_management_views.union_admin_promote_relegate_view,
        name="union-admin-promote-relegate",
    ),
    path(
        "union-admin/national-teams/",
        union_management_views.union_admin_national_teams_view,
        name="union-admin-national-teams",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/",
        union_management_views.union_admin_national_team_detail_view,
        name="union-admin-national-team-detail",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/members/",
        union_management_views.union_admin_national_team_members_view,
        name="union-admin-national-team-members",
    ),
    path(
        "union-admin/national-teams/<int:team_id>/members/<int:member_id>/",
        union_management_views.union_admin_national_team_member_detail_view,
        name="union-admin-national-team-member-detail",
    ),
    path(
        "union-admin/registration-applications/",
        union_management_views.union_admin_registration_applications_view,
        name="union-admin-registration-applications",
    ),
    path(
        "union-admin/registration-applications/<int:application_id>/",
        union_management_views.union_admin_registration_application_detail_view,
        name="union-admin-registration-application-detail",
    ),
    path(
        "union-admin/player-registration-submissions/",
        union_player_review_views.union_player_registration_submissions_view,
        name="union-player-registration-submissions",
    ),
    path(
        "union-admin/player-registration-submissions/<int:submission_id>/",
        union_player_review_views.union_player_registration_submission_detail_view,
        name="union-player-registration-submission-detail",
    ),
    path(
        "union-admin/player-registration-submissions/"
        "<int:submission_id>/assign-reviewer/",
        union_player_review_views.union_player_registration_assign_reviewer_view,
        name="union-player-registration-assign-reviewer",
    ),
    path(
        "union-admin/player-registration-submissions/"
        "<int:submission_id>/start-review/",
        union_player_review_views.union_player_registration_start_review_view,
        name="union-player-registration-start-review",
    ),
    path(
        "union-admin/player-registration-submissions/"
        "<int:submission_id>/request-changes/",
        union_player_review_views.union_player_registration_request_changes_view,
        name="union-player-registration-request-changes",
    ),
    path(
        "union-admin/player-registration-submissions/<int:submission_id>/approve/",
        union_player_review_views.union_player_registration_approve_view,
        name="union-player-registration-approve",
    ),
    path(
        "union-admin/player-registration-submissions/<int:submission_id>/reject/",
        union_player_review_views.union_player_registration_reject_view,
        name="union-player-registration-reject",
    ),
    path(
        "union-admin/player-registrations/",
        union_player_review_views.union_authoritative_player_registrations_view,
        name="union-authoritative-player-registrations",
    ),
    path(
        "union-admin/player-registrations/<int:registration_id>/",
        union_player_review_views.union_authoritative_player_registration_detail_view,
        name="union-authoritative-player-registration-detail",
    ),
    path(
        "union-admin/player-eligibilities/",
        union_player_eligibility_views.union_player_eligibilities_view,
        name="union-player-eligibilities",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/",
        union_player_eligibility_views.union_player_eligibility_detail_view,
        name="union-player-eligibility-detail",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/approve/",
        union_player_eligibility_views.union_player_eligibility_approve_view,
        name="union-player-eligibility-approve",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/reject/",
        union_player_eligibility_views.union_player_eligibility_reject_view,
        name="union-player-eligibility-reject",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/suspend/",
        union_player_eligibility_views.union_player_eligibility_suspend_view,
        name="union-player-eligibility-suspend",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/reinstate/",
        union_player_eligibility_views.union_player_eligibility_reinstate_view,
        name="union-player-eligibility-reinstate",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/expire/",
        union_player_eligibility_views.union_player_eligibility_expire_view,
        name="union-player-eligibility-expire",
    ),
    path(
        "union-admin/player-eligibilities/<int:eligibility_id>/cancel/",
        union_player_eligibility_views.union_player_eligibility_cancel_view,
        name="union-player-eligibility-cancel",
    ),
    path(
        "union-admin/player-transfers/",
        union_player_transfer_views.union_player_transfers_view,
        name="union-player-transfers",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/",
        union_player_transfer_views.union_player_transfer_detail_view,
        name="union-player-transfer-detail",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/record-offline-consent/",
        union_player_transfer_views.union_player_transfer_offline_consent_view,
        name="union-player-transfer-offline-consent",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/record-offline-decline/",
        union_player_transfer_views.union_player_transfer_offline_decline_view,
        name="union-player-transfer-offline-decline",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/request-changes/",
        union_player_transfer_views.union_player_transfer_request_changes_view,
        name="union-player-transfer-request-changes",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/reject/",
        union_player_transfer_views.union_player_transfer_reject_view,
        name="union-player-transfer-reject",
    ),
    path(
        "union-admin/player-transfers/<int:transfer_id>/approve/",
        union_player_transfer_views.union_player_transfer_approve_view,
        name="union-player-transfer-approve",
    ),
    path(
        "union-admin/official-readiness/",
        union_management_views.union_admin_official_readiness_view,
        name="union-admin-official-readiness",
    ),
    path(
        "union-admin/referees/",
        union_management_views.union_admin_match_officials_view,
        name="union-admin-match-officials",
    ),
    path(
        "union-admin/referees/<int:official_id>/",
        union_management_views.union_admin_match_official_detail_view,
        name="union-admin-match-official-detail",
    ),
    path(
        "union-admin/fixture-official-appointments/",
        union_management_views.union_admin_fixture_official_appointments_view,
        name="union-admin-fixture-official-appointments",
    ),
    path(
        "union-admin/fixture-official-appointments/<int:assignment_id>/",
        union_management_views.union_admin_fixture_official_appointment_detail_view,
        name="union-admin-fixture-official-appointment-detail",
    ),
    path(
        "union-admin/league-admin-scopes/",
        official_appointment_views.union_admin_league_admin_scopes_view,
        name="union-admin-league-admin-scopes",
    ),
    path(
        "union-admin/league-admin-scopes/<int:scope_id>/",
        official_appointment_views.union_admin_league_admin_scope_detail_view,
        name="union-admin-league-admin-scope-detail",
    ),
    # League/competition-scoped match official operations
    path(
        "league-admin/scopes/",
        official_appointment_views.league_admin_scopes_view,
        name="league-admin-scopes",
    ),
    path(
        "league-admin/fixtures/",
        official_appointment_views.league_admin_fixtures_view,
        name="league-admin-fixtures",
    ),
    path(
        "league-admin/match-officials/",
        official_appointment_views.league_admin_match_officials_view,
        name="league-admin-match-officials",
    ),
    path(
        "league-admin/fixture-official-appointments/",
        official_appointment_views.league_admin_appointments_view,
        name="league-admin-fixture-official-appointments",
    ),
    path(
        "league-admin/fixture-official-appointments/<int:assignment_id>/",
        official_appointment_views.league_admin_appointment_detail_view,
        name="league-admin-fixture-official-appointment-detail",
    ),
    # Match official self-service
    path(
        "match-official/appointments/",
        official_appointment_views.match_official_appointments_view,
        name="match-official-appointments",
    ),
    path(
        "match-official/appointments/<int:assignment_id>/response/",
        official_appointment_views.match_official_appointment_response_view,
        name="match-official-appointment-response",
    ),
    path(
        "union-admin/fixtures/<int:match_id>/reschedule/",
        union_management_views.union_admin_fixture_reschedule_view,
        name="union-admin-fixture-reschedule",
    ),
    path(
        "union-admin/generate-fixtures/",
        union_management_views.union_admin_generate_fixtures_view,
        name="union-admin-generate-fixtures",
    ),
    path(
        "super-admin/", views.super_admin_dashboard_view, name="super-admin-dashboard"
    ),
    path("referee/", views.referee_dashboard_view, name="referee-dashboard"),
    path(
        "ticketing-officer/",
        views.ticketing_officer_dashboard_view,
        name="ticketing-officer-dashboard",
    ),
    path("sponsor/", views.sponsor_dashboard_view, name="sponsor-dashboard"),
    # Public / No-auth endpoints (AllowAny)
    path(
        "public/fixtures/",
        views.public_fixtures_view,
        name="public-fixtures",
    ),
    path(
        "public/results/",
        views.public_results_view,
        name="public-results",
    ),
    path(
        "public/standings/",
        views.public_standings_view,
        name="public-standings",
    ),
    path(
        "public/clubs/",
        views.public_clubs_view,
        name="public-clubs",
    ),
    path(
        "public/unions/",
        views.public_unions_view,
        name="public-unions",
    ),
    path(
        "public/leagues/",
        views.public_leagues_view,
        name="public-leagues",
    ),
    path(
        "public/competitions/",
        views.public_competitions_view,
        name="public-competitions",
    ),
    # Match detail endpoint
    path(
        "public/matches/<int:match_id>/",
        views.public_match_detail_view,
        name="public-match-detail",
    ),
    # Standings calculation / recomputation endpoint
    path(
        "public/standings/calculate/",
        views.public_standings_calculation_view,
        name="public-standings-calculate",
    ),
]
