# Generated by Django 5.2.14 on 2026-06-24 10:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_roleapproval"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("SILVER", "Silver"),
                            ("GOLD", "Gold"),
                            ("PLATINUM", "Platinum"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMI_ANNUAL", "Semi-Annual"),
                            ("ANNUAL", "Annual"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("benefits", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_plans",
                        to="accounts.club",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name", "tier", "billing_cycle"],
            },
        ),
        migrations.CreateModel(
            name="MembershipSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=30,
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_at_next_cycle", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_subscriptions",
                        to="accounts.club",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="memberships.membershipplan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("MTN_MOMO", "MTN MoMo"),
                            ("AIRTEL_MONEY", "Airtel Money"),
                            ("FLUTTERWAVE", "Flutterwave"),
                            ("CARD", "Card"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MANUAL", "Manual"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("MTN", "MTN"),
                            ("AIRTEL", "Airtel"),
                            ("FLUTTERWAVE", "Flutterwave"),
                            ("MANUAL", "Manual"),
                        ],
                        default="MANUAL",
                        max_length=30,
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("provider_status", models.CharField(blank=True, max_length=60)),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("checkout_url", models.URLField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription_plan",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to="memberships.membershipplan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="memberships.membershipsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MembershipCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=40, unique=True)),
                ("qr_code_data", models.TextField(blank=True)),
                ("tier", models.CharField(max_length=20)),
                ("billing_cycle", models.CharField(max_length=20)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("REVOKED", "Revoked"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_cards",
                        to="accounts.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership_card",
                        to="memberships.membershipsubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(
                fields=["club", "is_active", "is_visible"],
                name="memberships_club_id_ac216c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(fields=["tier"], name="memberships_tier_20f936_idx"),
        ),
        migrations.AddIndex(
            model_name="membershipplan",
            index=models.Index(
                fields=["billing_cycle"], name="memberships_billing_d9a846_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipsubscription",
            index=models.Index(
                fields=["user", "status", "club"], name="memberships_user_id_068306_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipsubscription",
            index=models.Index(
                fields=["club", "status"], name="memberships_club_id_3518eb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipsubscription",
            index=models.Index(
                fields=["status", "ends_at"], name="memberships_status_d3a601_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="membershipsubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("user", "plan", "status"),
                name="unique_active_membership_subscription_per_user_plan",
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["subscription", "status"], name="memberships_subscri_3f3a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["provider", "status"], name="memberships_provide_1655ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["transaction_reference"], name="memberships_transac_1ea4c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershippayment",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="memberships_provide_c40097_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipcard",
            index=models.Index(
                fields=["user", "status", "valid_until"],
                name="memberships_user_id_6ac165_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="membershipcard",
            index=models.Index(
                fields=["club", "status"], name="memberships_club_id_fe392e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membershipcard",
            index=models.Index(
                fields=["card_number"], name="memberships_card_nu_88a353_idx"
            ),
        ),
    ]
