# Generated by Django 5.2.14 on 2026-07-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memberships", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipsubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING_PAYMENT", "Pending Payment"),
                    ("PENDING_APPROVAL", "Pending Approval"),
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("EXPIRED", "Expired"),
                    ("CANCELLED", "Cancelled"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING_PAYMENT",
                max_length=30,
            ),
        ),
    ]
