from django.urls import path

from . import views

urlpatterns = [
    # Public / fan-facing endpoints
    path(
        "matches/<int:match_id>/ticket-types/",
        views.match_ticket_types_view,
        name="ticketing-match-ticket-types",
    ),
    path(
        "orders/",
        views.my_ticket_orders_view,
        name="ticketing-orders",
    ),
    path(
        "orders/flutterwave/initialize/",
        views.ticket_order_flutterwave_initialize_view,
        name="ticketing-flutterwave-initialize",
    ),
    path(
        "tickets/me/",
        views.my_tickets_view,
        name="ticketing-my-tickets",
    ),
    path(
        "flutterwave/verify/",
        views.ticket_flutterwave_verify_view,
        name="ticketing-flutterwave-verify",
    ),
    path(
        "flutterwave/webhook/",
        views.ticket_flutterwave_webhook_view,
        name="ticketing-flutterwave-webhook",
    ),
    path(
        "validate/",
        views.ticket_validate_view,
        name="ticketing-validate",
    ),
    path(
        "reservations/expire/",
        views.expire_ticket_reservations_view,
        name="ticketing-expire-reservations",
    ),
    path(
        "tickets/<int:ticket_id>/qr/",
        views.ticket_qr_svg_view,
        name="ticketing-ticket-qr-svg",
    ),
    # Admin / management endpoints
    path(
        "admin/ticket-types/",
        views.admin_ticket_types_list_view,
        name="ticketing-admin-ticket-types-list",
    ),
    path(
        "admin/ticket-types/create/",
        views.admin_ticket_type_create_view,
        name="ticketing-admin-ticket-types-create",
    ),
    path(
        "admin/ticket-types/<int:pk>/",
        views.admin_ticket_type_detail_view,
        name="ticketing-admin-ticket-types-detail",
    ),
    path(
        "admin/ticket-types/<int:pk>/update/",
        views.admin_ticket_type_update_view,
        name="ticketing-admin-ticket-types-update",
    ),
    path(
        "admin/ticket-types/<int:pk>/delete/",
        views.admin_ticket_type_delete_view,
        name="ticketing-admin-ticket-types-delete",
    ),
    path(
        "admin/ticket-types/<int:pk>/inventory/",
        views.admin_ticket_type_inventory_view,
        name="ticketing-admin-ticket-types-inventory",
    ),
    path(
        "admin/ticket-types/<int:pk>/publish/",
        views.admin_ticket_type_publish_view,
        name="ticketing-admin-ticket-types-publish",
    ),
    path(
        "admin/matches/<int:match_id>/publish-sale/",
        views.admin_match_publish_sale_view,
        name="ticketing-admin-match-publish-sale",
    ),
    path(
        "admin/sales-monitoring/",
        views.admin_sales_monitoring_view,
        name="ticketing-admin-sales-monitoring",
    ),
]
