# Generated by Django 5.2.14 on 2026-07-03 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("USER_GROWTH", "User Growth"),
                            ("ENGAGEMENT", "Engagement"),
                            ("MEMBERSHIP", "Membership"),
                            ("TICKETING", "Ticketing"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("SYSTEM_HEALTH", "System Health"),
                            ("REVENUE", "Revenue"),
                            ("PLATFORM_SUMMARY", "Platform Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        help_text="e.g., daily, weekly, monthly", max_length=20
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("computed_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "period", "-start_date"],
                        name="analytics_c_metric__56eb69_idx",
                    ),
                    models.Index(
                        fields=["-computed_at"], name="analytics_c_compute_498d04_idx"
                    ),
                ],
                "unique_together": {
                    ("metric_type", "period", "start_date", "end_date")
                },
            },
        ),
        migrations.CreateModel(
            name="ReportAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("USER_GROWTH", "User Growth"),
                            ("ENGAGEMENT", "Engagement"),
                            ("MEMBERSHIP", "Membership"),
                            ("TICKETING", "Ticketing"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("SYSTEM_HEALTH", "System Health"),
                            ("REVENUE", "Revenue"),
                            ("PLATFORM_SUMMARY", "Platform Summary"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("VIEW", "View"),
                            ("EXPORT", "Export"),
                            ("PRINT", "Print"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filters_applied", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="analytics_r_user_id_a456b3_idx",
                    ),
                    models.Index(
                        fields=["report_type", "-created_at"],
                        name="analytics_r_report__bdb1d1_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="analytics_r_action_b6ef3c_idx",
                    ),
                ],
            },
        ),
    ]
