# Generated by Django 5.2.14 on 2026-06-16 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "stage_type",
                    models.CharField(
                        choices=[
                            ("SINGLE", "Single Stage"),
                            ("GROUP_KO", "Group Stage + Knockout"),
                            ("MULTI", "Multi Stage"),
                            ("SWISS", "Swiss System"),
                            ("CUSTOM", "Custom"),
                        ],
                        default="SINGLE",
                        help_text="The structural type of the competition format",
                        max_length=20,
                    ),
                ),
                (
                    "has_home_and_away",
                    models.BooleanField(
                        default=True,
                        help_text="Whether teams play both home and away (double round robin)",
                    ),
                ),
                (
                    "max_teams_default",
                    models.PositiveIntegerField(
                        default=16, help_text="Default maximum number of teams"
                    ),
                ),
                (
                    "min_teams_default",
                    models.PositiveIntegerField(
                        default=2, help_text="Default minimum number of teams"
                    ),
                ),
                (
                    "groups_count",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Number of groups (if applicable)",
                    ),
                ),
                (
                    "teams_per_group",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Teams per group (if applicable)",
                    ),
                ),
                (
                    "teams_qualify_per_group",
                    models.PositiveIntegerField(
                        blank=True,
                        default=0,
                        help_text="Number of teams that qualify from each group",
                    ),
                ),
                ("has_third_place_match", models.BooleanField(default=False)),
                ("has_replays", models.BooleanField(default=False)),
                (
                    "has_aggregate",
                    models.BooleanField(
                        default=False, help_text="Two-legged aggregate ties"
                    ),
                ),
                ("away_goals_rule", models.BooleanField(default=False)),
                (
                    "tie_breakers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Ordered list of tie-breaking criteria (e.g. ['goal_difference', 'goals_scored', 'head_to_head'])",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Competition Format",
                "verbose_name_plural": "Competition Formats",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SportVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="governance/sport_variants/"
                    ),
                ),
                (
                    "players_per_team",
                    models.PositiveIntegerField(
                        default=11, help_text="Number of players per team on the field"
                    ),
                ),
                (
                    "max_substitutes",
                    models.PositiveIntegerField(
                        default=5, help_text="Maximum number of substitutes allowed"
                    ),
                ),
                (
                    "match_duration_minutes",
                    models.PositiveIntegerField(
                        default=90, help_text="Standard match duration in minutes"
                    ),
                ),
                ("has_halftime", models.BooleanField(default=True)),
                (
                    "halftime_duration_minutes",
                    models.PositiveIntegerField(
                        default=15, help_text="Halftime break duration in minutes"
                    ),
                ),
                ("has_extra_time", models.BooleanField(default=False)),
                (
                    "extra_time_duration_minutes",
                    models.PositiveIntegerField(
                        default=30, help_text="Extra time duration in minutes"
                    ),
                ),
                ("has_penalties", models.BooleanField(default=False)),
                (
                    "max_red_cards_default",
                    models.PositiveIntegerField(
                        default=1, help_text="Default red cards before forfeit"
                    ),
                ),
                ("points_win", models.PositiveIntegerField(default=3)),
                ("points_draw", models.PositiveIntegerField(default=1)),
                ("points_loss", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this variant is available for use",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True once the variant has been verified by a super admin",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sport Variant",
                "verbose_name_plural": "Sport Variants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300)),
                (
                    "rule_number",
                    models.CharField(
                        blank=True,
                        help_text="Official rule number/code if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("COMPLIANCE", "Compliance & Legal"),
                            ("COMPETITION", "Competition Rules"),
                            ("FINANCIAL", "Financial Regulations"),
                            ("DISCIPLINARY", "Disciplinary & Ethics"),
                            ("PLAYER_ELIG", "Player Eligibility"),
                            ("REGISTRATION", "Registration & Transfers"),
                            ("TECHNICAL", "Technical Standards"),
                            ("SAFETY", "Safety & Security"),
                            ("BROADCAST", "Broadcast & Media"),
                            ("MARKETING", "Marketing & Branding"),
                            ("OTHER", "Other"),
                        ],
                        default="COMPETITION",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("MANDATORY", "Mandatory"),
                            ("RECOMMENDED", "Recommended"),
                            ("ADVISORY", "Advisory"),
                        ],
                        default="MANDATORY",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed explanation of the rule"),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="Short summary for quick reference",
                        max_length=500,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("effective_date", models.DateField(blank=True, null=True)),
                (
                    "enforcement_notes",
                    models.TextField(
                        blank=True,
                        help_text="How this rule is enforced and penalties for non-compliance",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this rule is published to leagues",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_rules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        help_text="Previous version of this rule that this one replaces",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="governance.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rule & Standard",
                "verbose_name_plural": "Rules & Standards",
                "ordering": ["category", "title"],
                "unique_together": {("slug", "version")},
            },
        ),
        migrations.CreateModel(
            name="LeagueStandard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the league has accepted the standard",
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accepted_standards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_standards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_standards",
                        to="dashboards.league",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_assignments",
                        to="governance.rule",
                    ),
                ),
            ],
            options={
                "verbose_name": "League Standard Assignment",
                "verbose_name_plural": "League Standard Assignments",
                "ordering": ["-assigned_at"],
                "unique_together": {("rule", "league")},
            },
        ),
    ]
