# Generated by Django 5.2.14 on 2026-07-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("DEBUG", "Debug"),
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("logger_name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("path", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("status_code", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_email", models.CharField(blank=True, max_length=150)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["level", "-created_at"],
                        name="monitoring__level_b8c7a5_idx",
                    ),
                    models.Index(
                        fields=["logger_name"], name="monitoring__logger__f3856d_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="monitoring__created_06214f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Anomaly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anomaly_type", models.CharField(max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("RESOLVED", "Resolved"),
                            ("FALSE_POSITIVE", "False Positive"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("detection_source", models.CharField(max_length=100)),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                (
                    "related_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "affected_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_anomalies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="monitoring__status_fd4eea_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="monitoring__severit_cc94cf_idx",
                    ),
                    models.Index(
                        fields=["anomaly_type"], name="monitoring__anomaly_5a02cb_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DATA_PROTECTION", "Data Protection"),
                            ("FINANCIAL", "Financial Regulation"),
                            ("SPORTS_GOVERNANCE", "Sports Governance"),
                            ("ANTI_CORRUPTION", "Anti-Corruption"),
                            ("TAX", "Tax Compliance"),
                            ("EMPLOYMENT", "Employment Law"),
                            ("SAFETY", "Safety & Security"),
                        ],
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("regulation_reference", models.CharField(blank=True, max_length=100)),
                ("is_compliant", models.BooleanField(default=True)),
                ("violation_details", models.TextField(blank=True)),
                ("corrective_action", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="compliance_trails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["category", "-created_at"],
                        name="monitoring__categor_1fe802_idx",
                    ),
                    models.Index(
                        fields=["is_compliant"], name="monitoring__is_comp_72baaf_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DataAccessAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_type",
                    models.CharField(
                        choices=[
                            ("READ", "Read"),
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("EXPORT", "Export"),
                            ("IMPORT", "Import"),
                        ],
                        max_length=20,
                    ),
                ),
                ("resource_type", models.CharField(max_length=100)),
                ("resource_id", models.PositiveIntegerField(blank=True, null=True)),
                ("resource_name", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("is_authorized", models.BooleanField(default=True)),
                ("denial_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_access_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="monitoring__user_id_9d467d_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "-created_at"],
                        name="monitoring__resourc_2deaf9_idx",
                    ),
                    models.Index(
                        fields=["is_authorized", "-created_at"],
                        name="monitoring__is_auth_207887_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("TICKETING", "Ticketing"),
                            ("MEMBERSHIP", "Membership"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("WALLET", "Wallet"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Payment Initiated"),
                            ("COMPLETED", "Payment Completed"),
                            ("FAILED", "Payment Failed"),
                            ("REFUNDED", "Payment Refunded"),
                            ("CHARGEBACK", "Chargeback"),
                            ("DISPUTED", "Disputed"),
                            ("CANCELLED", "Payment Cancelled"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("reference", models.CharField(max_length=100)),
                ("provider", models.CharField(max_length=50)),
                ("provider_reference", models.CharField(blank=True, max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="monitoring__user_id_5fd5d9_idx",
                    ),
                    models.Index(
                        fields=["payment_source", "-created_at"],
                        name="monitoring__payment_de4146_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="monitoring__event_t_a94570_idx",
                    ),
                    models.Index(
                        fields=["reference"], name="monitoring__referen_18735a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILURE", "Login Failure"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PERMISSION_DENIED", "Permission Denied"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                            ("DATA_BREACH", "Data Breach"),
                            ("BRUTE_FORCE", "Brute Force Attempt"),
                            ("ACCOUNT_LOCKOUT", "Account Lockout"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="monitoring__event_t_2eb5fe_idx",
                    ),
                    models.Index(
                        fields=["severity", "-created_at"],
                        name="monitoring__severit_7397c8_idx",
                    ),
                    models.Index(
                        fields=["is_resolved", "-created_at"],
                        name="monitoring__is_reso_4f0770_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TransactionReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("source_system", models.CharField(max_length=50)),
                ("external_reference", models.CharField(max_length=100)),
                ("internal_reference", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("MATCHED", "Matched"),
                            ("UNMATCHED", "Unmatched"),
                            ("DISCREPANCY", "Discrepancy"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-transaction_date"],
                        name="monitoring__status_6dc983_idx",
                    ),
                    models.Index(
                        fields=["source_system"], name="monitoring__source__82c20c_idx"
                    ),
                    models.Index(
                        fields=["external_reference"],
                        name="monitoring__externa_6aacc8_idx",
                    ),
                    models.Index(
                        fields=["internal_reference"],
                        name="monitoring__interna_2e8d86_idx",
                    ),
                ],
            },
        ),
    ]
