# Generated by Django 5.2.14 on 2026-07-08 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("monitoring", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ApprovalLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("SUBMITTED", "Submitted"),
                            ("VERIFIED", "Verified"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ROLE_MANAGEMENT", "Role Management"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("PAYMENT", "Payment"),
                            ("COMPLIANCE", "Compliance"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approvals_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Log",
                "verbose_name_plural": "Approval Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChargebackRefund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_object_id", models.PositiveIntegerField()),
                (
                    "dispute_type",
                    models.CharField(
                        choices=[
                            ("CHARGEBACK", "Chargeback"),
                            ("REFUND_REQUEST", "Refund Request"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("INVESTIGATING", "Investigating"),
                            ("WON", "Won (Chargeback)"),
                            ("LOST", "Lost (Chargeback)"),
                            ("REFUNDED", "Refunded"),
                            ("REJECTED", "Rejected (Refund)"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Reason provided by the customer for the dispute."
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=3)),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Links or details of evidence submitted.",
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes on how the dispute was resolved.",
                    ),
                ),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The admin who resolved the dispute.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_handled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "opened_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who initiated the dispute.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disputes_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chargeback & Refund",
                "verbose_name_plural": "Chargebacks & Refunds",
                "ordering": ["-opened_at"],
            },
        ),
    ]
