# Generated by Django 5.2.14 on 2026-07-08 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_admin",
            "0003_broadcast_helpcenterarticle_notificationtemplate_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="broadcast",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="featureflag",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="helpcenterarticle",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="notificationtemplate",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="publiccontent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="systemmessage",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="Announcement",
        ),
        migrations.DeleteModel(
            name="Banner",
        ),
        migrations.DeleteModel(
            name="Broadcast",
        ),
        migrations.DeleteModel(
            name="FeatureFlag",
        ),
        migrations.DeleteModel(
            name="HelpCenterArticle",
        ),
        migrations.DeleteModel(
            name="NotificationTemplate",
        ),
        migrations.DeleteModel(
            name="PublicContent",
        ),
        migrations.DeleteModel(
            name="SystemMessage",
        ),
    ]
