# Generated by Django 5.2.14 on 2026-06-25 18:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0006_alter_notificationpreference_event_type"),
        ("dashboards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyCompetition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("RUGBY", "Rugby"),
                            ("FOOTBALL", "Football"),
                            ("BASKETBALL", "Basketball"),
                            ("OTHER", "Other"),
                        ],
                        default="RUGBY",
                        max_length=30,
                    ),
                ),
                ("season", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open"),
                            ("LOCKED", "Locked"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("squad_size", models.PositiveIntegerField(default=15)),
                ("lineup_size", models.PositiveIntegerField(default=15)),
                ("max_players_per_club", models.PositiveIntegerField(default=4)),
                (
                    "captain_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("2.00"),
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("1.00")),
                            django.core.validators.MaxValueValidator(Decimal("5.00")),
                        ],
                    ),
                ),
                (
                    "min_player_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("4.00"), max_digits=6
                    ),
                ),
                (
                    "max_player_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("15.00"), max_digits=6
                    ),
                ),
                (
                    "default_player_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=6
                    ),
                ),
                ("rules_summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_fantasy_competitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "linked_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_competitions",
                        to="dashboards.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="FantasyGameweek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("number", models.PositiveIntegerField()),
                ("start_at", models.DateTimeField()),
                ("lock_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPCOMING", "Upcoming"),
                            ("OPEN", "Open"),
                            ("LOCKED", "Locked"),
                            ("SCORING", "Scoring"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="UPCOMING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweeks",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "matches",
                    models.ManyToManyField(
                        blank=True,
                        related_name="fantasy_gameweeks",
                        to="dashboards.match",
                    ),
                ),
            ],
            options={
                "ordering": ["fantasy_competition", "number"],
            },
        ),
        migrations.CreateModel(
            name="FantasyLeague",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "league_type",
                    models.CharField(
                        choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                        default="PUBLIC",
                        max_length=20,
                    ),
                ),
                ("join_code", models.CharField(blank=True, max_length=20, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_fantasy_leagues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_leagues",
                        to="fantasy.fantasycompetition",
                    ),
                ),
            ],
            options={
                "ordering": ["fantasy_competition", "name"],
            },
        ),
        migrations.CreateModel(
            name="FantasyLineup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now=True)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineups",
                        to="fantasy.fantasygameweek",
                    ),
                ),
            ],
            options={
                "ordering": ["gameweek", "fantasy_team"],
            },
        ),
        migrations.CreateModel(
            name="FantasyPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=160)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("PROP", "Prop"),
                            ("HOOKER", "Hooker"),
                            ("LOCK", "Lock"),
                            ("BACK_ROW", "Back Row"),
                            ("SCRUM_HALF", "Scrum Half"),
                            ("FLY_HALF", "Fly Half"),
                            ("CENTRE", "Centre"),
                            ("WING", "Wing"),
                            ("FULLBACK", "Fullback"),
                            ("GOALKEEPER", "Goalkeeper"),
                            ("DEFENDER", "Defender"),
                            ("MIDFIELDER", "Midfielder"),
                            ("FORWARD", "Forward"),
                            ("GUARD", "Guard"),
                            ("FORWARD_BASKETBALL", "Basketball Forward"),
                            ("CENTER_BASKETBALL", "Basketball Center"),
                            ("UTILITY", "Utility"),
                        ],
                        default="UTILITY",
                        max_length=40,
                    ),
                ),
                (
                    "calculated_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=6
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("5.00"), max_digits=6
                    ),
                ),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Auto Calculated"),
                            ("MANUAL", "Manual Override"),
                        ],
                        default="AUTO",
                        max_length=20,
                    ),
                ),
                ("price_override_reason", models.TextField(blank=True)),
                ("price_locked_at", models.DateTimeField(blank=True, null=True)),
                ("previous_stats", models.JSONField(blank=True, default=dict)),
                (
                    "current_form",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_available", models.BooleanField(default=True)),
                ("availability_note", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_players",
                        to="accounts.club",
                    ),
                ),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="fantasy.fantasycompetition",
                    ),
                ),
            ],
            options={
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="FantasyLineupPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_starter", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "lineup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="fantasy.fantasylineup",
                    ),
                ),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineup_entries",
                        to="fantasy.fantasyplayer",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="fantasylineup",
            name="captain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="captain_lineups",
                to="fantasy.fantasyplayer",
            ),
        ),
        migrations.AddField(
            model_name="fantasylineup",
            name="vice_captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="vice_captain_lineups",
                to="fantasy.fantasyplayer",
            ),
        ),
        migrations.CreateModel(
            name="FantasyPlayerGameweekScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=8
                    ),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_fantasy_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_fantasy_scores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweek_scores",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_scores",
                        to="fantasy.fantasygameweek",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fantasy_player_scores",
                        to="dashboards.match",
                    ),
                ),
            ],
            options={
                "ordering": ["gameweek", "fantasy_player"],
            },
        ),
        migrations.CreateModel(
            name="FantasyTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "total_points",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("current_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fantasy_teams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["fantasy_competition", "current_rank", "name"],
            },
        ),
        migrations.CreateModel(
            name="FantasySquadPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_at_selection",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("removed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fantasy_player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_selections",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_players",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddField(
            model_name="fantasylineup",
            name="fantasy_team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lineups",
                to="fantasy.fantasyteam",
            ),
        ),
        migrations.CreateModel(
            name="FantasyLeagueMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "fantasy_league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="fantasy.fantasyleague",
                    ),
                ),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to="fantasy.fantasyteam",
                    ),
                ),
            ],
            options={
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="FantasyTeamGameweekScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "points",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gameweek_scores",
                        to="fantasy.fantasyteam",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_scores",
                        to="fantasy.fantasygameweek",
                    ),
                ),
            ],
            options={
                "ordering": ["gameweek", "rank", "-points"],
            },
        ),
        migrations.AddIndex(
            model_name="fantasycompetition",
            index=models.Index(
                fields=["status", "sport"], name="fantasy_fan_status_c1e6d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasycompetition",
            index=models.Index(
                fields=["linked_competition", "status"],
                name="fantasy_fan_linked__47deaa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasygameweek",
            index=models.Index(
                fields=["fantasy_competition", "status"],
                name="fantasy_fan_fantasy_48b364_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasygameweek",
            index=models.Index(
                fields=["lock_at", "status"], name="fantasy_fan_lock_at_8c3a7d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasygameweek",
            unique_together={("fantasy_competition", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="fantasyleague",
            unique_together={("fantasy_competition", "name")},
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["fantasy_competition", "is_active"],
                name="fantasy_fan_fantasy_2f5878_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["club", "position"], name="fantasy_fan_club_id_4cc949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayer",
            index=models.Index(
                fields=["final_price"], name="fantasy_fan_final_p_e6cb26_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasyplayer",
            unique_together={("fantasy_competition", "display_name", "club")},
        ),
        migrations.AlterUniqueTogether(
            name="fantasylineupplayer",
            unique_together={("lineup", "fantasy_player")},
        ),
        migrations.AddIndex(
            model_name="fantasyplayergameweekscore",
            index=models.Index(
                fields=["gameweek", "status"], name="fantasy_fan_gamewee_588c0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyplayergameweekscore",
            index=models.Index(
                fields=["fantasy_player", "gameweek"],
                name="fantasy_fan_fantasy_a34b51_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasyplayergameweekscore",
            unique_together={("fantasy_player", "gameweek")},
        ),
        migrations.AddIndex(
            model_name="fantasyteam",
            index=models.Index(
                fields=["owner", "fantasy_competition"],
                name="fantasy_fan_owner_i_deec73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyteam",
            index=models.Index(
                fields=["fantasy_competition", "-total_points"],
                name="fantasy_fan_fantasy_1ead67_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasyteam",
            unique_together={("owner", "fantasy_competition")},
        ),
        migrations.AddConstraint(
            model_name="fantasysquadplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("fantasy_team", "fantasy_player"),
                name="unique_active_fantasy_squad_player",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasylineup",
            index=models.Index(
                fields=["gameweek", "submitted_at"],
                name="fantasy_fan_gamewee_9abc58_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasylineup",
            unique_together={("fantasy_team", "gameweek")},
        ),
        migrations.AlterUniqueTogether(
            name="fantasyleaguemembership",
            unique_together={("fantasy_league", "fantasy_team")},
        ),
        migrations.AddIndex(
            model_name="fantasyteamgameweekscore",
            index=models.Index(
                fields=["gameweek", "-points"], name="fantasy_fan_gamewee_b915de_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasyteamgameweekscore",
            index=models.Index(
                fields=["fantasy_team", "gameweek"],
                name="fantasy_fan_fantasy_4d4069_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fantasyteamgameweekscore",
            unique_together={("fantasy_team", "gameweek")},
        ),
    ]
