# Generated by Django 5.2.14 on 2026-07-07 03:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0002_alter_fantasyleague_join_code"),
        ("governance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyEligibilityRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("AGE_MIN", "Minimum Age"),
                            ("AGE_MAX", "Maximum Age"),
                            ("NATIONALITY_RESTRICTION", "Nationality Restriction"),
                            ("LEAGUE_RESTRICTION", "League Restriction"),
                            ("INJURY_EXCLUSION", "Injury Exclusion"),
                            ("SUSPENSION_EXCLUSION", "Suspension Exclusion"),
                            ("INTERNATIONAL_DUTY", "International Duty Restriction"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value or criteria for the rule", max_length=255
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rule_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="fantasy_fan_rule_ty_a4923d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FantasyPriceStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "price_type",
                    models.CharField(
                        choices=[
                            ("MIN_PRICE", "Minimum Player Price"),
                            ("MAX_PRICE", "Maximum Player Price"),
                            ("DEFAULT_PRICE", "Default Player Price"),
                            ("BUDGET", "Team Budget"),
                            ("PRICE_CHANGE_THRESHOLD", "Price Change Threshold"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=8)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["price_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["price_type", "is_active"],
                        name="fantasy_fan_price_t_003314_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FantasyScoringRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("TRY", "Try"),
                            ("CONVERSION", "Conversion"),
                            ("PENALTY_GOAL", "Penalty Goal"),
                            ("DROP_GOAL", "Drop Goal"),
                            ("TACKLE", "Tackle"),
                            ("ASSIST", "Assist"),
                            ("CLEAN_SHEET", "Clean Sheet"),
                            ("MAN_OF_THE_MATCH", "Man of the Match"),
                            ("YELLOW_CARD", "Yellow Card"),
                            ("RED_CARD", "Red Card"),
                            ("OWN_GOAL", "Own Goal"),
                            ("PLAYED", "Played (60+ mins)"),
                            ("GOAL", "Goal"),
                            ("SAVE", "Save (Goalkeeper)"),
                            ("CUSTOM", "Custom Event"),
                        ],
                        max_length=30,
                    ),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=5)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_rule", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "is_active"],
                        name="fantasy_fan_event_t_a6558a_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="fantasy_fan_is_acti_810d83_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FantasySquadRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("MIN_SQUAD_SIZE", "Minimum Squad Size"),
                            ("MAX_SQUAD_SIZE", "Maximum Squad Size"),
                            ("MIN_LINEUP_SIZE", "Minimum Lineup Size"),
                            ("MAX_LINEUP_SIZE", "Maximum Lineup Size"),
                            ("MAX_PLAYERS_PER_CLUB", "Max Players per Club"),
                            ("MIN_PLAYERS_PER_POSITION", "Min Players per Position"),
                            ("MAX_PLAYERS_PER_POSITION", "Max Players per Position"),
                            ("CAPTAIN_ALLOWED", "Captain Allowed"),
                            ("VICE_CAPTAIN_ALLOWED", "Vice Captain Allowed"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.IntegerField()),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Applicable position if any",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rule_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="fantasy_fan_rule_ty_e9b30f_idx",
                    ),
                    models.Index(
                        fields=["position"], name="fantasy_fan_positio_ddb018_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FantasyTransferRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("TRANSFER_LIMIT", "Transfer Limit per Gameweek"),
                            ("TRANSFER_COST", "Transfer Cost"),
                            ("ROLLOVER_TRANSFERS", "Rollover Unused Transfers"),
                            ("FREE_TRANSFERS", "Free Transfers"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.IntegerField(help_text="Numeric value for the rule")),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["rule_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["rule_type", "is_active"],
                        name="fantasy_fan_rule_ty_398917_idx",
                    ),
                    models.Index(
                        fields=["effective_from"], name="fantasy_fan_effecti_f8bd21_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FantasyCompetitionMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition_format",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fantasy_mappings",
                        to="governance.competitionformat",
                    ),
                ),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="governance_mappings",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_fantasy_mappings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sport_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fantasy_mappings",
                        to="governance.sportvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("fantasy_competition",)},
            },
        ),
        migrations.CreateModel(
            name="FantasyFeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature_name",
                    models.CharField(
                        choices=[
                            ("FANTASY_ENABLED", "Enable Fantasy Module"),
                            ("TRANSFERS_ENABLED", "Enable Transfers"),
                            ("LEAGUES_ENABLED", "Enable Fantasy Leagues"),
                            ("AUTO_SCORING", "Enable Auto-Scoring"),
                            ("MANUAL_SCORING", "Enable Manual Scoring Override"),
                            ("PRICE_CHANGES", "Enable Dynamic Price Changes"),
                            ("PUBLIC_LEAGUES", "Enable Public Leagues"),
                            ("PRIVATE_LEAGUES", "Enable Private Leagues"),
                            ("CAPTAIN_MODE", "Enable Captain Mode"),
                            ("VICE_CAPTTAIN_MODE", "Enable Vice Captain Mode"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("is_enabled", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True)),
                ("enabled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enabled_fantasy_features",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["feature_name"],
                "indexes": [
                    models.Index(
                        fields=["is_enabled"], name="fantasy_fan_is_enab_866286_idx"
                    )
                ],
            },
        ),
    ]
