# Generated by Django 5.2.14 on 2026-06-25 21:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fantasy", "0002_alter_fantasyleague_join_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FantasyTransferWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("opens_at", models.DateTimeField()),
                ("closes_at", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
                ("free_transfers", models.PositiveIntegerField(default=1)),
                ("max_transfers_per_window", models.PositiveIntegerField(default=3)),
                (
                    "points_cost_per_extra_transfer",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("4.00"), max_digits=6
                    ),
                ),
                (
                    "allow_trades",
                    models.BooleanField(
                        default=False,
                        help_text="Reserved for future team-to-team trade flows. MVP transfers use direct player swaps.",
                    ),
                ),
                (
                    "allow_transfers_after_lineup_lock",
                    models.BooleanField(default=False),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfer_windows",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfer_windows",
                        to="fantasy.fantasygameweek",
                    ),
                ),
            ],
            options={
                "ordering": ["fantasy_competition", "opens_at"],
            },
        ),
        migrations.CreateModel(
            name="FantasyTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[("TRANSFER", "Transfer"), ("TRADE", "Trade")],
                        default="TRANSFER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="COMPLETED",
                        max_length=30,
                    ),
                ),
                (
                    "points_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=6
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "fantasy_competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="fantasy.fantasycompetition",
                    ),
                ),
                (
                    "fantasy_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="fantasy.fantasyteam",
                    ),
                ),
                (
                    "gameweek",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="fantasy.fantasygameweek",
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="fantasy.fantasyplayer",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_fantasy_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer_window",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers",
                        to="fantasy.fantasytransferwindow",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="fantasytransferwindow",
            index=models.Index(
                fields=["fantasy_competition", "is_active"],
                name="fantasy_fan_fantasy_6731df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransferwindow",
            index=models.Index(
                fields=["opens_at", "closes_at"], name="fantasy_fan_opens_a_357553_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransferwindow",
            index=models.Index(
                fields=["gameweek"], name="fantasy_fan_gamewee_8dd862_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransfer",
            index=models.Index(
                fields=["fantasy_team", "status"], name="fantasy_fan_fantasy_dd9cd1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransfer",
            index=models.Index(
                fields=["fantasy_competition", "created_at"],
                name="fantasy_fan_fantasy_81e8f9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransfer",
            index=models.Index(
                fields=["transfer_window", "status"],
                name="fantasy_fan_transfe_d9ae8b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fantasytransfer",
            index=models.Index(
                fields=["gameweek", "status"], name="fantasy_fan_gamewee_e17a6f_idx"
            ),
        ),
    ]
