# Generated by Django 5.2.14 on 2026-06-12 10:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sponsor_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATE", "Corporate"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "registration_country",
                    models.CharField(
                        default="UG",
                        help_text="ISO 3166-1 alpha-2 country code where the sponsor is registered.",
                        max_length=2,
                    ),
                ),
                (
                    "brn",
                    models.CharField(
                        blank=True,
                        help_text="Business Registration Number for corporate sponsors.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "tin",
                    models.CharField(
                        blank=True,
                        help_text="Tax Identification Number for corporate sponsors.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_sponsor_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorAccountMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "member_role",
                    models.CharField(
                        choices=[
                            ("OWNER", "Owner"),
                            ("ADMIN", "Admin"),
                            ("FINANCE", "Finance"),
                            ("VIEWER", "Viewer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="sponsorships.sponsoraccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sponsor_account", "user__email"],
            },
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(
                fields=["sponsor_type"], name="sponsorship_sponsor_9d355f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(fields=["status"], name="sponsorship_status_10cf4d_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(fields=["owner"], name="sponsorship_owner_i_876f86_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(
                fields=["registration_country"], name="sponsorship_registr_e5497c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(
                fields=["registration_country", "brn"],
                name="sponsorship_registr_dcc590_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoraccount",
            index=models.Index(
                fields=["registration_country", "tin"],
                name="sponsorship_registr_311242_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("sponsor_type", "CORPORATE"),
                    ("brn__isnull", False),
                    models.Q(("brn", ""), _negated=True),
                ),
                fields=("registration_country", "brn"),
                name="unique_corporate_sponsor_brn_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoraccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("sponsor_type", "CORPORATE"),
                    ("tin__isnull", False),
                    models.Q(("tin", ""), _negated=True),
                ),
                fields=("registration_country", "tin"),
                name="unique_corporate_sponsor_tin_per_country",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoraccount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("sponsor_type", "INDIVIDUAL"),
                    models.Q(
                        ("brn__isnull", False), models.Q(("brn", ""), _negated=True)
                    ),
                    models.Q(
                        ("tin__isnull", False), models.Q(("tin", ""), _negated=True)
                    ),
                    _connector="OR",
                ),
                name="corporate_sponsor_requires_brn_or_tin",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoraccountmember",
            index=models.Index(
                fields=["sponsor_account", "member_role"],
                name="sponsorship_sponsor_59d8a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoraccountmember",
            index=models.Index(
                fields=["user", "is_active"], name="sponsorship_user_id_17bda0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsoraccountmember",
            constraint=models.UniqueConstraint(
                fields=("sponsor_account", "user"), name="unique_sponsor_account_member"
            ),
        ),
    ]
