# Generated by Django 5.2.14 on 2026-06-15 16:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorships", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "owner_type",
                    models.CharField(
                        choices=[
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("UNION", "Union / Federation"),
                            ("PLATFORM", "Platform"),
                            ("SPORT", "Sport"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "owner_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Temporary identifier until the owner module is fully linked.",
                        max_length=100,
                    ),
                ),
                ("owner_name", models.CharField(max_length=255)),
                (
                    "scope_type",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Player"),
                            ("TEAM", "Team"),
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("COMPETITION", "Competition"),
                            ("UNION", "Union / Federation"),
                            ("SPORT", "Sport"),
                            ("EVENT", "Event"),
                            ("MATCH", "Match"),
                            ("PLATFORM", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Temporary identifier until target models are fully linked.",
                        max_length=100,
                    ),
                ),
                ("scope_name", models.CharField(max_length=255)),
                (
                    "sponsor_type_allowed",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("CORPORATE", "Corporate"),
                            ("BOTH", "Both"),
                        ],
                        default="BOTH",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General"),
                            ("BEVERAGE", "Beverage"),
                            ("BANKING", "Banking"),
                            ("TELECOM", "Telecom"),
                            ("BETTING", "Betting"),
                            ("TRANSPORT", "Transport"),
                            ("INSURANCE", "Insurance"),
                            ("EDUCATION", "Education"),
                            ("MEDIA", "Media"),
                            ("HEALTHCARE", "Healthcare"),
                            ("MERCHANDISE", "Merchandise"),
                            ("OTHER", "Other"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("is_exclusive", models.BooleanField(default=False)),
                ("requires_platform_fee", models.BooleanField(default=False)),
                (
                    "platform_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "activation_rule",
                    models.CharField(
                        choices=[
                            ("AFTER_FULL_PAYMENT", "After Full Payment"),
                            ("AFTER_FIRST_PAYMENT", "After First Payment"),
                            ("AFTER_ADMIN_APPROVAL", "After Admin Approval"),
                            ("AFTER_PLATFORM_FEE", "After Platform Fee"),
                            ("IMMEDIATE", "Immediate"),
                        ],
                        default="AFTER_ADMIN_APPROVAL",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_sponsor_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sponsor_packages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["owner_type", "owner_name", "name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("FREE_TICKETS", "Free Tickets"),
                            ("DISCOUNTED_TICKETS", "Discounted Tickets"),
                            ("RESERVED_SEATING", "Reserved Seating"),
                            ("VIP_ACCESS", "VIP Access"),
                            ("DIGITAL_BADGE", "Digital Badge"),
                            ("PUBLIC_RECOGNITION", "Public Recognition"),
                            ("LOGO_PLACEMENT", "Logo Placement"),
                            ("HOMEPAGE_AD", "Homepage Advert"),
                            ("FAN_DASHBOARD_AD", "Fan Dashboard Advert"),
                            ("EMAIL_CAMPAIGN", "Email Campaign"),
                            ("PUSH_NOTIFICATION", "Push Notification"),
                            ("MERCHANDISE_DISCOUNT", "Merchandise Discount"),
                            ("CAMPAIGN_ANALYTICS", "Campaign Analytics"),
                            ("OTHER", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "discount_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "value_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("requires_payment_confirmation", models.BooleanField(default=True)),
                (
                    "is_platform_controlled",
                    models.BooleanField(
                        default=False,
                        help_text="Controls benefits only League OS can provide.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["sponsor_package", "benefit_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=80)),
                (
                    "agreement_type",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("IN_KIND", "In-kind"),
                            ("EXISTING_CONTRACT", "Existing Contract"),
                            ("PLATFORM_ADVERT", "Platform Advert"),
                        ],
                        default="CASH",
                        max_length=30,
                    ),
                ),
                (
                    "payment_source",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "Paid Through Platform"),
                            ("OFF_PLATFORM", "Paid Off Platform"),
                            ("IN_KIND", "In-kind"),
                            ("EXISTING_CONTRACT", "Existing Contract"),
                            ("FREE", "Free / Waived"),
                        ],
                        default="PLATFORM",
                        max_length=30,
                    ),
                ),
                (
                    "payment_model",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("RECURRING", "Recurring"),
                            ("INSTALLMENT", "Installment"),
                            ("EXTERNAL", "External"),
                            ("FREE", "Free"),
                        ],
                        default="ONE_TIME",
                        max_length=30,
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("PENDING_PAYMENT", "Pending Payment"),
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("EXPIRED", "Expired"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("platform_fee_required", models.BooleanField(default=False)),
                (
                    "platform_fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "platform_fee_status",
                    models.CharField(
                        choices=[
                            ("NOT_REQUIRED", "Not Required"),
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("WAIVED", "Waived"),
                        ],
                        default="NOT_REQUIRED",
                        max_length=30,
                    ),
                ),
                ("platform_activation_allowed", models.BooleanField(default=False)),
                (
                    "benefits_tier",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic"),
                            ("DIGITAL", "Digital"),
                            ("PREMIUM", "Premium"),
                            ("REVENUE_SHARE", "Revenue Share"),
                        ],
                        default="BASIC",
                        max_length=30,
                    ),
                ),
                (
                    "activation_rule",
                    models.CharField(
                        choices=[
                            ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                            ("PLATFORM_FEE_CONFIRMED", "Platform Fee Confirmed"),
                            ("ADMIN_APPROVAL", "Admin Approval"),
                            ("WAIVED", "Waived"),
                        ],
                        default="ADMIN_APPROVAL",
                        max_length=40,
                    ),
                ),
                ("waiver_status", models.CharField(blank=True, max_length=30)),
                ("waiver_reason", models.TextField(blank=True)),
                ("waived_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("proof_reference", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_sponsor_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sponsor_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="sponsorships.sponsoraccount",
                    ),
                ),
                (
                    "waived_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="waived_sponsor_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="agreements",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueShareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Player"),
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("UNION", "Union / Federation"),
                            ("PLATFORM", "Platform"),
                            ("EVENT_OWNER", "Event Owner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_identifier", models.CharField(blank=True, max_length=100)),
                ("recipient_name", models.CharField(max_length=255)),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fixed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_platform_share", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_share_rules",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_share_rules",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["recipient_type", "recipient_name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("MOBILE_MONEY", "Mobile Money"),
                            ("CARD", "Card"),
                            ("CHEQUE", "Cheque"),
                            ("OTHER", "Other"),
                        ],
                        default="BANK_TRANSFER",
                        max_length=30,
                    ),
                ),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("REJECTED", "Rejected"),
                            ("REFUNDED", "Refunded"),
                            ("PARTIALLY_REFUNDED", "Partially Refunded"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("proof_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="confirmed_sponsor_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_sponsor_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RevenueDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Player"),
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("UNION", "Union / Federation"),
                            ("PLATFORM", "Platform"),
                            ("EVENT_OWNER", "Event Owner"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("recipient_identifier", models.CharField(blank=True, max_length=100)),
                ("recipient_name", models.CharField(max_length=255)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ALLOCATED", "Allocated"),
                            ("PAID_OUT", "Paid Out"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_distributions",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revenue_distributions",
                        to="sponsorships.sponsorpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["agreement", "recipient_type", "recipient_name"],
            },
        ),
        migrations.CreateModel(
            name="SponsorPaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_type",
                    models.CharField(
                        choices=[
                            ("ONE_TIME", "One-time"),
                            ("RECURRING", "Recurring"),
                            ("INSTALLMENT", "Installment"),
                            ("PLATFORM_FEE", "Platform Fee"),
                        ],
                        max_length=30,
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField(default=1)),
                ("due_date", models.DateField()),
                ("period_start", models.DateField(blank=True, null=True)),
                ("period_end", models.DateField(blank=True, null=True)),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("PAID", "Paid"),
                            ("OVERDUE", "Overdue"),
                            ("WAIVED", "Waived"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedules",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
            ],
            options={
                "ordering": ["agreement", "sequence_number", "due_date"],
            },
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="payment_schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="sponsorships.sponsorpaymentschedule",
            ),
        ),
        migrations.CreateModel(
            name="SponsorWorkflowEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PACKAGE_CREATED", "Package Created"),
                            ("PACKAGE_SUBMITTED", "Package Submitted"),
                            ("PACKAGE_APPROVED", "Package Approved"),
                            ("PACKAGE_REJECTED", "Package Rejected"),
                            ("AGREEMENT_CREATED", "Agreement Created"),
                            ("AGREEMENT_SUBMITTED", "Agreement Submitted"),
                            ("AGREEMENT_APPROVED", "Agreement Approved"),
                            ("AGREEMENT_REJECTED", "Agreement Rejected"),
                            ("PAYMENT_REGISTERED", "Payment Registered"),
                            ("PAYMENT_CONFIRMED", "Payment Confirmed"),
                            ("PAYMENT_REJECTED", "Payment Rejected"),
                            ("PLATFORM_FEE_WAIVED", "Platform Fee Waived"),
                            ("BENEFIT_ISSUED", "Benefit Issued"),
                            ("AGREEMENT_ACTIVATED", "Agreement Activated"),
                            ("AGREEMENT_PAUSED", "Agreement Paused"),
                            ("AGREEMENT_EXPIRED", "Agreement Expired"),
                            ("AGREEMENT_CANCELLED", "Agreement Cancelled"),
                        ],
                        max_length=40,
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=40)),
                ("to_status", models.CharField(blank=True, max_length=40)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsor_workflow_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_events",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_events",
                        to="sponsorships.sponsorpayment",
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workflow_events",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["owner_type", "owner_identifier"],
                name="sponsorship_owner_t_1ef443_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["scope_type", "scope_identifier"],
                name="sponsorship_scope_t_2d14d6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["category"], name="sponsorship_categor_98e783_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(fields=["status"], name="sponsorship_status_e13ebb_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["is_exclusive"], name="sponsorship_is_excl_0b5341_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorbenefit",
            index=models.Index(
                fields=["benefit_type"], name="sponsorship_benefit_0d811d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorbenefit",
            index=models.Index(
                fields=["is_platform_controlled"], name="sponsorship_is_plat_ae2ea9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoragreement",
            index=models.Index(
                fields=["sponsor_account", "status"],
                name="sponsorship_sponsor_16ef41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoragreement",
            index=models.Index(
                fields=["sponsor_package", "status"],
                name="sponsorship_sponsor_dce161_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoragreement",
            index=models.Index(
                fields=["payment_source"], name="sponsorship_payment_999d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoragreement",
            index=models.Index(
                fields=["payment_model"], name="sponsorship_payment_ff8753_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsoragreement",
            index=models.Index(
                fields=["starts_at", "ends_at"], name="sponsorship_starts__580ed8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuesharerule",
            index=models.Index(
                fields=["recipient_type"], name="sponsorship_recipie_529663_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuesharerule",
            index=models.Index(
                fields=["is_platform_share"], name="sponsorship_is_plat_fef063_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuedistribution",
            index=models.Index(
                fields=["agreement", "status"], name="sponsorship_agreeme_448b5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuedistribution",
            index=models.Index(
                fields=["payment", "status"], name="sponsorship_payment_2cbefa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenuedistribution",
            index=models.Index(
                fields=["recipient_type"], name="sponsorship_recipie_0b534d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpaymentschedule",
            index=models.Index(
                fields=["agreement", "status"], name="sponsorship_agreeme_8cc07d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpaymentschedule",
            index=models.Index(
                fields=["schedule_type"], name="sponsorship_schedul_9c7329_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpaymentschedule",
            index=models.Index(
                fields=["due_date"], name="sponsorship_due_dat_fb348a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorpaymentschedule",
            constraint=models.UniqueConstraint(
                fields=("agreement", "sequence_number"),
                name="unique_sponsor_payment_schedule_sequence",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpayment",
            index=models.Index(
                fields=["agreement", "status"], name="sponsorship_agreeme_9b3633_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpayment",
            index=models.Index(
                fields=["payment_schedule", "status"],
                name="sponsorship_payment_ea4250_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpayment",
            index=models.Index(
                fields=["transaction_reference"], name="sponsorship_transac_c74d59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorworkflowevent",
            index=models.Index(
                fields=["event_type"], name="sponsorship_event_t_005323_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorworkflowevent",
            index=models.Index(fields=["actor"], name="sponsorship_actor_i_846d9b_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorworkflowevent",
            index=models.Index(
                fields=["created_at"], name="sponsorship_created_c6d8f6_idx"
            ),
        ),
    ]
