# Generated by Django 5.2.14 on 2026-06-16 12:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sponsorships",
            "0002_sponsorpackage_sponsorbenefit_sponsoragreement_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsorpayment",
            name="checkout_initialized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="checkout_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="provider",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("FLUTTERWAVE", "Flutterwave")],
                default="MANUAL",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="provider_response",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="provider_status",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sponsorpayment",
            name="provider_transaction_id",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="sponsorpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("MOBILE_MONEY", "Mobile Money"),
                    ("CARD", "Card"),
                    ("CHEQUE", "Cheque"),
                    ("FLUTTERWAVE", "Flutterwave"),
                    ("OTHER", "Other"),
                ],
                default="BANK_TRANSFER",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="sponsorpayment",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONFIRMED", "Confirmed"),
                    ("REJECTED", "Rejected"),
                    ("FAILED", "Failed"),
                    ("CANCELLED", "Cancelled"),
                    ("REFUNDED", "Refunded"),
                    ("PARTIALLY_REFUNDED", "Partially Refunded"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpayment",
            index=models.Index(
                fields=["provider", "provider_status"],
                name="sponsorship_provide_e94f2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpayment",
            index=models.Index(
                fields=["provider_transaction_id"],
                name="sponsorship_provide_dbecc6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sponsorpayment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("transaction_reference", ""), _negated=True),
                fields=("transaction_reference",),
                name="unique_sponsor_payment_transaction_reference",
            ),
        ),
    ]
