# Generated by Django 5.2.14 on 2026-07-07 06:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorships", "0003_sponsorpayment_checkout_initialized_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignVisibilitySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "visibility_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public"),
                            ("RESTRICTED", "Restricted"),
                            ("PRIVATE", "Private"),
                            ("PLATFORM_ONLY", "Platform Only"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "allowed_owner_types",
                    models.JSONField(
                        default=list, help_text="List of allowed owner types"
                    ),
                ),
                (
                    "allowed_categories",
                    models.JSONField(
                        default=list, help_text="List of allowed sponsor categories"
                    ),
                ),
                ("max_active_campaigns", models.PositiveIntegerField(default=10)),
                ("requires_approval", models.BooleanField(default=True)),
                ("auto_publish", models.BooleanField(default=False)),
                (
                    "placement_rules",
                    models.JSONField(
                        default=dict, help_text="Placement positioning rules"
                    ),
                ),
                (
                    "display_settings",
                    models.JSONField(default=dict, help_text="Display configuration"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["visibility_level", "name"],
                "indexes": [
                    models.Index(
                        fields=["visibility_level", "is_active"],
                        name="sponsorship_visibil_27d26d_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SponsorshipApprovalWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "workflow_type",
                    models.CharField(
                        choices=[
                            ("PACKAGE_APPROVAL", "Package Approval"),
                            ("AGREEMENT_APPROVAL", "Agreement Approval"),
                            ("PAYMENT_APPROVAL", "Payment Approval"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "steps",
                    models.JSONField(
                        default=list, help_text="Ordered list of approval steps"
                    ),
                ),
                ("requires_finance_approval", models.BooleanField(default=False)),
                ("requires_legal_approval", models.BooleanField(default=False)),
                (
                    "auto_approve_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-approve if value below threshold",
                        max_digits=14,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["workflow_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["workflow_type", "is_active"],
                        name="sponsorship_workflo_c096bf_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="sponsorship_is_defa_d18479_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "placement_type",
                    models.CharField(
                        choices=[
                            ("HOMEPAGE_BANNER", "Homepage Banner"),
                            ("HOMEPAGE_SIDEBAR", "Homepage Sidebar"),
                            ("LEAGUE_PAGE", "League Page"),
                            ("CLUB_PAGE", "Club Page"),
                            ("MATCH_PAGE", "Match Page"),
                            ("FAN_DASHBOARD", "Fan Dashboard"),
                            ("EMAIL_HEADER", "Email Header"),
                            ("PUSH_NOTIFICATION", "Push Notification"),
                            ("IN_APP_BANNER", "In-App Banner"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "max_slots",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum sponsors for this placement"
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0, help_text="Higher priority = more prominent"
                    ),
                ),
                (
                    "dimensions",
                    models.JSONField(
                        default=dict,
                        help_text="Placement dimensions and specifications",
                    ),
                ),
                (
                    "pricing_rules",
                    models.JSONField(
                        default=dict, help_text="Pricing rules for this placement"
                    ),
                ),
                (
                    "targeting_rules",
                    models.JSONField(
                        default=dict, help_text="Targeting and rotation rules"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_exclusive", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-priority", "placement_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["placement_type", "is_active"],
                        name="sponsorship_placeme_6820a3_idx",
                    ),
                    models.Index(
                        fields=["is_exclusive"], name="sponsorship_is_excl_7e740b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BenefitSharingPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("REVENUE_SHARE", "Revenue Share Policy"),
                            ("BENEFIT_DISTRIBUTION", "Benefit Distribution Policy"),
                            ("PLATFORM_FEE", "Platform Fee Policy"),
                            ("PAYOUT_SCHEDULE", "Payout Schedule Policy"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "rules",
                    models.JSONField(
                        default=dict, help_text="Policy rules and configurations"
                    ),
                ),
                (
                    "minimum_payout",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "payout_frequency",
                    models.CharField(default="MONTHLY", max_length=30),
                ),
                (
                    "applies_to",
                    models.JSONField(
                        default=dict, help_text="Which entities this policy applies to"
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_benefit_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_benefit_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["policy_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["policy_type", "is_active"],
                        name="sponsorship_policy__180a20_idx",
                    ),
                    models.Index(
                        fields=["is_default"], name="sponsorship_is_defa_755da1_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("IMPRESSIONS", "Impressions"),
                            ("CLICKS", "Clicks"),
                            ("CONVERSIONS", "Conversions"),
                            ("ENGAGEMENT_RATE", "Engagement Rate"),
                            ("ROI", "Return on Investment"),
                            ("REACH", "Reach"),
                            ("BRAND_AWARENESS", "Brand Awareness"),
                        ],
                        max_length=30,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="calculated_campaign_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_metrics",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "sponsor_package", "metric_type"],
                "indexes": [
                    models.Index(
                        fields=["sponsor_package", "metric_type"],
                        name="sponsorship_sponsor_8ad822_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="sponsorship_period__93b769_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ComplianceAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "audit_type",
                    models.CharField(
                        choices=[
                            ("KYC_VERIFICATION", "KYC Verification"),
                            ("DOCUMENT_AUDIT", "Document Audit"),
                            ("PAYMENT_AUDIT", "Payment Audit"),
                            ("BENEFIT_AUDIT", "Benefit Audit"),
                            ("CONTRACT_AUDIT", "Contract Audit"),
                            ("COMPLIANCE_REVIEW", "Compliance Review"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("WAIVED", "Waived"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                (
                    "findings",
                    models.JSONField(
                        default=dict, help_text="Audit findings and issues"
                    ),
                ),
                (
                    "remediation_steps",
                    models.JSONField(
                        default=list, help_text="Required remediation steps"
                    ),
                ),
                ("auditor_notes", models.TextField(blank=True)),
                ("performed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_audits",
                        to="sponsorships.sponsoragreement",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_compliance_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_compliance_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_audits",
                        to="sponsorships.sponsoraccount",
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compliance_audits",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["audit_type", "status"],
                        name="sponsorship_audit_t_947c7a_idx",
                    ),
                    models.Index(
                        fields=["sponsor_account"],
                        name="sponsorship_sponsor_1d7e40_idx",
                    ),
                    models.Index(
                        fields=["next_review_date"],
                        name="sponsorship_next_re_80daae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SponsorFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "framework_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT_TIER", "Payment Tier Configuration"),
                            ("COMMISSION_STRUCTURE", "Commission Structure"),
                            ("APPROVAL_WORKFLOW", "Approval Workflow"),
                            ("VISIBILITY_SETTINGS", "Visibility Settings"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, help_text="Framework configuration"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("effective_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sponsor_frameworks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_sponsor_frameworks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["framework_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["framework_type", "is_active"],
                        name="sponsorship_framewo_45c6b2_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="sponsorship_is_acti_d7317b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SponsorshipInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                (
                    "inventory_type",
                    models.CharField(
                        choices=[
                            ("PACKAGE_SLOT", "Package Slot"),
                            ("PLACEMENT_SLOT", "Placement Slot"),
                            ("BENEFIT_QUOTA", "Benefit Quota"),
                            ("CAMPAIGN_SLOT", "Campaign Slot"),
                        ],
                        max_length=30,
                    ),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                ("allocated_quantity", models.PositiveIntegerField(default=0)),
                ("available_quantity", models.PositiveIntegerField(default=0)),
                (
                    "allocation_rules",
                    models.JSONField(
                        default=dict, help_text="Rules for allocating this inventory"
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "belongs_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="sponsorships.systemplacement",
                    ),
                ),
            ],
            options={
                "ordering": ["inventory_type", "name"],
                "indexes": [
                    models.Index(
                        fields=["inventory_type", "is_active"],
                        name="sponsorship_invento_9c81b0_idx",
                    )
                ],
            },
        ),
    ]
