# Generated by Django 5.2.14 on 2026-07-14 21:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsorships", "0004_campaignvisibilitysettings_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorshipOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("PLAYER", "Player"),
                            ("TEAM", "Team"),
                            ("CLUB", "Club"),
                            ("LEAGUE", "League"),
                            ("COMPETITION", "Competition"),
                            ("UNION", "Union / Federation"),
                            ("SPORT", "Sport"),
                            ("EVENT", "Event"),
                            ("MATCH", "Match"),
                            ("PLATFORM", "Platform"),
                        ],
                        max_length=20,
                    ),
                ),
                ("property_identifier", models.CharField(blank=True, max_length=120)),
                ("property_name", models.CharField(max_length=255)),
                (
                    "sport",
                    models.CharField(
                        choices=[
                            ("GENERAL", "All Sports"),
                            ("RUGBY", "Rugby"),
                            ("FOOTBALL", "Football"),
                            ("BASKETBALL", "Basketball"),
                            ("COMMUNITY", "Community Sport"),
                        ],
                        default="GENERAL",
                        max_length=30,
                    ),
                ),
                (
                    "location",
                    models.CharField(blank=True, default="Uganda", max_length=120),
                ),
                (
                    "price_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("starts_at", models.DateField(blank=True, null=True)),
                ("ends_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("RESERVED", "Reserved"),
                            ("CLOSED", "Closed"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["property_type", "property_name"],
            },
        ),
        migrations.AddField(
            model_name="sponsorpackage",
            name="duration_type",
            field=models.CharField(
                choices=[
                    ("ONE_MATCH", "One Match"),
                    ("ONE_EVENT", "One Event"),
                    ("MONTHLY", "Monthly"),
                    ("SEASON", "Season-long"),
                ],
                default="SEASON",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sponsorpackage",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sponsorpackage",
            name="objective",
            field=models.CharField(
                choices=[
                    ("VISIBILITY", "Brand Visibility"),
                    ("FAN_ENGAGEMENT", "Fan Engagement"),
                    ("HOSPITALITY", "Hospitality"),
                    ("COMMUNITY_IMPACT", "Community Impact"),
                    ("GRASSROOTS", "Grassroots Development"),
                ],
                default="VISIBILITY",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="sponsorpackage",
            name="sport",
            field=models.CharField(
                choices=[
                    ("GENERAL", "All Sports"),
                    ("RUGBY", "Rugby"),
                    ("FOOTBALL", "Football"),
                    ("BASKETBALL", "Basketball"),
                    ("COMMUNITY", "Community Sport"),
                ],
                default="GENERAL",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["is_template"], name="sponsorship_is_temp_6254ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["objective"], name="sponsorship_objecti_39c5e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(
                fields=["duration_type"], name="sponsorship_duratio_1ddf7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorpackage",
            index=models.Index(fields=["sport"], name="sponsorship_sport_ccb9cd_idx"),
        ),
        migrations.AddField(
            model_name="sponsorshipopportunity",
            name="sponsor_package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="sponsorships.sponsorpackage",
            ),
        ),
        migrations.AddField(
            model_name="sponsoragreement",
            name="opportunity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agreements",
                to="sponsorships.sponsorshipopportunity",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorshipopportunity",
            index=models.Index(
                fields=["sponsor_package", "status"],
                name="sponsorship_sponsor_7658bd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorshipopportunity",
            index=models.Index(
                fields=["property_type"], name="sponsorship_propert_299f0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorshipopportunity",
            index=models.Index(fields=["sport"], name="sponsorship_sport_3fc6cb_idx"),
        ),
        migrations.AddIndex(
            model_name="sponsorshipopportunity",
            index=models.Index(
                fields=["location"], name="sponsorship_locatio_e7d535_idx"
            ),
        ),
    ]
