# Generated by Django 5.2.14 on 2026-06-17 19:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dashboards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("payment_reference", models.CharField(blank=True, max_length=120)),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=120),
                ),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=10)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("quantity_sold", models.PositiveIntegerField(default=0)),
                ("sale_start_at", models.DateTimeField(blank=True, null=True)),
                ("sale_end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SOLD_OUT", "Sold Out"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_ticket_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="dashboards.match",
                    ),
                ),
            ],
            options={
                "ordering": ["match", "price", "name"],
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_code",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("USED", "Used"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_in_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_in_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="dashboards.match",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="ticketing.ticketorder",
                    ),
                ),
                (
                    "ticket_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tickets",
                        to="ticketing.tickettype",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketValidationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scanned_code", models.CharField(max_length=120)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("VALID", "Valid"),
                            ("INVALID", "Invalid"),
                            ("ALREADY_USED", "Already Used"),
                            ("CANCELLED", "Cancelled"),
                            ("WRONG_MATCH", "Wrong Match"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_validation_logs",
                        to="dashboards.match",
                    ),
                ),
                (
                    "scanned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_validation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_logs",
                        to="ticketing.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["buyer", "status"], name="ticketing_t_buyer_i_4cb71b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["status", "created_at"], name="ticketing_t_status_be65d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["payment_reference"], name="ticketing_t_payment_7e58e4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickettype",
            index=models.Index(
                fields=["match", "status"], name="ticketing_t_match_i_29cb5b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tickettype",
            index=models.Index(fields=["status"], name="ticketing_t_status_e4d786_idx"),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.UniqueConstraint(
                fields=("match", "name"), name="unique_ticket_type_name_per_match"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["match", "status"], name="ticketing_t_match_i_188213_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticket",
            index=models.Index(
                fields=["owner", "status"], name="ticketing_t_owner_i_ca1272_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["scanned_code"], name="ticketing_t_scanned_3246bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["result", "created_at"], name="ticketing_t_result_f3c14a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketvalidationlog",
            index=models.Index(
                fields=["match", "created_at"], name="ticketing_t_match_i_0855be_idx"
            ),
        ),
    ]
