# Generated by Django 5.2.14 on 2026-06-23 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="checkout_initialized_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="checkout_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="provider",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("FLUTTERWAVE", "Flutterwave")],
                default="FLUTTERWAVE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="provider_status",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["provider", "provider_status"],
                name="ticketing_t_provide_3defaa_idx",
            ),
        ),
        migrations.AddField(
            model_name="ticketorderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="ticketing.ticketorder",
            ),
        ),
        migrations.AddField(
            model_name="ticketorderitem",
            name="ticket_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="ticketing.tickettype",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketorderitem",
            index=models.Index(
                fields=["order", "ticket_type"], name="ticketing_t_order_i_3f3090_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketorderitem",
            index=models.Index(
                fields=["ticket_type"], name="ticketing_t_ticket__1e165f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketorderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "ticket_type"),
                name="unique_ticket_type_per_ticket_order",
            ),
        ),
    ]
