# Generated by Django 5.2.14 on 2026-06-25 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ticketing",
            "0002_ticketorderitem_ticketorder_checkout_initialized_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ticketorder",
            name="reservation_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticketorder",
            name="reservation_released_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="ticketorder",
            index=models.Index(
                fields=["status", "reservation_expires_at"],
                name="ticketing_t_status_826a5c_idx",
            ),
        ),
    ]
