# Generated by Django 5.2.14 on 2026-07-21 06:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("memberships", "0002_alter_membershipsubscription_status"),
        (
            "sponsorships",
            "0005_sponsorshipopportunity_sponsorpackage_duration_type_and_more",
        ),
        ("ticketing", "0003_ticketorder_reservation_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated if blank.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("MEMBERSHIP_FEE", "Membership Fee"),
                            ("TICKET_PURCHASE", "Ticket Purchase"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=255)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("PARTIALLY_PAID", "Partially Paid"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("paid_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "download_url",
                    models.URLField(
                        blank=True, help_text="URL to download PDF if available."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="memberships.membershippayment",
                    ),
                ),
                (
                    "sponsor_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="sponsorships.sponsorpayment",
                    ),
                ),
                (
                    "ticket_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="ticketing.ticketorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated if blank.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("MEMBERSHIP_FEE", "Membership Fee"),
                            ("TICKET_PURCHASE", "Ticket Purchase"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=255)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("payment_method", models.CharField(blank=True, max_length=60)),
                ("transaction_reference", models.CharField(blank=True, max_length=120)),
                ("issue_date", models.DateTimeField(blank=True, null=True)),
                ("payment_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "download_url",
                    models.URLField(
                        blank=True, help_text="URL to download PDF if available."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipts",
                        to="accounts.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="finances.invoice",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "membership_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="memberships.membershippayment",
                    ),
                ),
                (
                    "sponsor_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="sponsorships.sponsorpayment",
                    ),
                ),
                (
                    "ticket_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="ticketing.ticketorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FinanceAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INVOICE_CREATED", "Invoice Created"),
                            ("INVOICE_UPDATED", "Invoice Updated"),
                            ("RECEIPT_GENERATED", "Receipt Generated"),
                            ("PAYMENT_UPDATED", "Payment Updated"),
                            ("REPORT_VIEWED", "Report Viewed"),
                            ("FINANCIAL_RECORD_MODIFIED", "Financial Record Modified"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Model name of the target object.",
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.PositiveIntegerField(
                        blank=True, help_text="ID of the target object.", null=True
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the target.",
                        max_length=255,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.CharField(blank=True, max_length=45)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_audit_logs",
                        to="accounts.club",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Audit Log",
                "verbose_name_plural": "Finance Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "action"], name="finances_fi_club_id_2339a6_idx"
                    ),
                    models.Index(
                        fields=["actor", "action"],
                        name="finances_fi_actor_i_afca50_idx",
                    ),
                    models.Index(
                        fields=["action"], name="finances_fi_action_185c45_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="finances_fi_created_d52e0a_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="finances_fi_target__a0e52c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["club", "status"], name="finances_in_club_id_174d5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["club", "payment_type"], name="finances_in_club_id_46d239_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["invoice_number"], name="finances_in_invoice_47786a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issue_date"], name="finances_in_issue_d_0accea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["club", "payment_type"], name="finances_re_club_id_a69d25_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["receipt_number"], name="finances_re_receipt_21cbaf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receipt",
            index=models.Index(
                fields=["issue_date"], name="finances_re_issue_d_335c0c_idx"
            ),
        ),
    ]
