from django.urls import path

from . import views

urlpatterns = [
    path(
        "competitions/",
        views.fantasy_competition_list_view,
        name="fantasy-competition-list",
    ),
    path(
        "competitions/<int:competition_id>/",
        views.fantasy_competition_detail_view,
        name="fantasy-competition-detail",
    ),
    path(
        "competitions/<int:competition_id>/gameweeks/",
        views.fantasy_competition_gameweeks_view,
        name="fantasy-competition-gameweeks",
    ),
    path(
        "competitions/<int:competition_id>/players/",
        views.fantasy_player_market_view,
        name="fantasy-player-market",
    ),
    path(
        "teams/",
        views.fantasy_team_create_view,
        name="fantasy-team-create",
    ),
    path(
        "teams/me/",
        views.my_fantasy_teams_view,
        name="fantasy-my-teams",
    ),
    path(
        "teams/<int:team_id>/",
        views.fantasy_team_detail_view,
        name="fantasy-team-detail",
    ),
    path(
        "teams/<int:team_id>/history/",
        views.fantasy_team_history_view,
        name="fantasy-team-history",
    ),
    path(
        "teams/<int:team_id>/squad/",
        views.fantasy_team_squad_update_view,
        name="fantasy-team-squad-update",
    ),
    path(
        "teams/<int:team_id>/lineups/",
        views.fantasy_team_lineup_submit_view,
        name="fantasy-team-lineup-submit",
    ),
    path(
        "lineups/me/",
        views.my_lineups_view,
        name="fantasy-my-lineups",
    ),
    path(
        "leagues/",
        views.fantasy_league_create_view,
        name="fantasy-league-create",
    ),
    path(
        "leagues/available/",
        views.fantasy_league_available_view,
        name="fantasy-league-available",
    ),
    path(
        "leagues/join/",
        views.fantasy_league_join_view,
        name="fantasy-league-join",
    ),
    path(
        "leagues/my/",
        views.my_fantasy_leagues_view,
        name="fantasy-my-leagues",
    ),
    path(
        "leagues/<int:league_id>/",
        views.fantasy_league_detail_view,
        name="fantasy-league-detail",
    ),
    path(
        "leagues/<int:league_id>/leaderboard/",
        views.fantasy_league_leaderboard_view,
        name="fantasy-league-leaderboard",
    ),
    path(
        "gameweeks/<int:gameweek_id>/leaderboard/",
        views.fantasy_gameweek_leaderboard_view,
        name="fantasy-gameweek-leaderboard",
    ),
    path(
        "admin/competitions/",
        views.admin_fantasy_competition_create_view,
        name="fantasy-admin-competition-create",
    ),
    path(
        "admin/gameweeks/",
        views.admin_fantasy_gameweek_create_view,
        name="fantasy-admin-gameweek-create",
    ),
    path(
        "admin/players/",
        views.admin_fantasy_player_create_view,
        name="fantasy-admin-player-create",
    ),
    path(
        "admin/players/<int:player_id>/price/",
        views.admin_fantasy_player_price_update_view,
        name="fantasy-admin-player-price-update",
    ),
    path(
        "admin/gameweeks/<int:gameweek_id>/player-scores/",
        views.admin_gameweek_player_score_view,
        name="fantasy-admin-player-score",
    ),
    path(
        "admin/player-scores/<int:score_id>/approve/",
        views.admin_player_score_approve_view,
        name="fantasy-admin-player-score-approve",
    ),
    path(
        "admin/gameweeks/<int:gameweek_id>/calculate/",
        views.admin_gameweek_calculate_view,
        name="fantasy-admin-gameweek-calculate",
    ),
    path(
        "admin/gameweeks/<int:gameweek_id>/close/",
        views.admin_gameweek_close_view,
        name="fantasy-admin-gameweek-close",
    ),
]
