# Generated by Django 5.2.14 on 2026-06-25 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pollvote",
            name="unique_poll_vote_per_user",
        ),
    ]
