# Generated by Django 5.2.14 on 2026-07-21 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("club_operations", "0001_initial"),
        ("dashboards", "0019_union_transfer_loan_return"),
        (
            "sponsorships",
            "0005_sponsorshipopportunity_sponsorpackage_duration_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SponsorCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("objective", models.TextField(blank=True)),
                (
                    "campaign_type",
                    models.CharField(
                        choices=[
                            ("MATCHDAY", "Matchday Activation"),
                            ("DIGITAL", "Digital Campaign"),
                            ("COMMUNITY", "Community Activation"),
                            ("HOSPITALITY", "Hospitality Event"),
                            ("MEDIA", "Media Campaign"),
                            ("MERCHANDISING", "Merchandising"),
                            ("OTHER", "Other"),
                        ],
                        default="MATCHDAY",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SCHEDULED", "Scheduled"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "budget",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("expected_reach", models.PositiveIntegerField(default=0)),
                ("branding_requirements", models.TextField(blank=True)),
                ("deliverables", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sponsor_campaigns",
                        to="accounts.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_sponsor_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_campaigns",
                        to="sponsorships.sponsoraccount",
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_campaigns",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activation_notes", models.TextField(blank=True)),
                (
                    "branding_locations",
                    models.TextField(
                        blank=True, help_text="e.g., perimeter boards, LED boards"
                    ),
                ),
                ("booth_requirements", models.TextField(blank=True)),
                ("banner_locations", models.TextField(blank=True)),
                ("led_board_allocation", models.CharField(blank=True, max_length=255)),
                ("vip_allocation", models.PositiveIntegerField(default=0)),
                (
                    "activation_status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ACTIVE", "Active"),
                            ("EXECUTED", "Executed"),
                            ("PENDING", "Pending Review"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaign_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_assignments",
                        to="dashboards.match",
                    ),
                ),
                (
                    "sponsor_package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_assignments",
                        to="sponsorships.sponsorpackage",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="club_operations.sponsorcampaign",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketingOfficerAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_role",
                    models.CharField(
                        choices=[
                            ("GATE_CONTROLLER", "Gate Controller"),
                            ("TICKET_SCANNER", "Ticket Scanner"),
                            ("TICKET_SELLER", "Ticket Seller"),
                            ("CUSTOMER_SERVICE", "Customer Service"),
                            ("SUPERVISOR", "Ticketing Supervisor"),
                        ],
                        default="TICKET_SCANNER",
                        max_length=30,
                    ),
                ),
                ("gate_allocation", models.CharField(blank=True, max_length=100)),
                ("shift_start", models.DateTimeField()),
                ("shift_end", models.DateTimeField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked In"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_officer_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticketing_officer_assignments",
                        to="accounts.club",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticketing_officer_assignments",
                        to="dashboards.match",
                    ),
                ),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticketing_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["match__match_date", "shift_start", "officer__email"],
            },
        ),
        migrations.CreateModel(
            name="MatchdayOperationTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("TICKETING", "Ticketing"),
                            ("SECURITY", "Security"),
                            ("MEDICAL", "Medical"),
                            ("MARKETING", "Marketing"),
                            ("SPONSORSHIP", "Sponsorship"),
                            ("HOSPITALITY", "Hospitality"),
                            ("STADIUM_PREP", "Stadium Preparation"),
                            ("ACCREDITATION", "Accreditation"),
                            ("VOLUNTEERS", "Volunteers"),
                            ("MEDIA", "Media"),
                            ("TRANSPORT", "Transport"),
                            ("CATERING", "Catering"),
                            ("OTHER", "Other"),
                        ],
                        default="STADIUM_PREP",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("due_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("OVERDUE", "Overdue"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("completion_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matchday_tasks_assigned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_tasks",
                        to="accounts.club",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_matchday_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_matchday_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_tasks",
                        to="dashboards.match",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "priority", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "status"], name="club_operat_club_id_f388ee_idx"
                    ),
                    models.Index(
                        fields=["match", "status"],
                        name="club_operat_match_i_45c4bf_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="club_operat_assigne_5c8c94_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="club_operat_categor_ff4f13_idx",
                    ),
                    models.Index(
                        fields=["due_date"], name="club_operat_due_dat_cb156b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchdayReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("REVIEWED", "Reviewed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("review_notes", models.TextField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("attendance_tickets_sold", models.PositiveIntegerField(default=0)),
                (
                    "attendance_complimentary_tickets",
                    models.PositiveIntegerField(default=0),
                ),
                ("attendance_estimated", models.PositiveIntegerField(default=0)),
                (
                    "revenue_ticket",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "revenue_merchandise",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "revenue_other",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("sponsor_campaigns_executed", models.TextField(blank=True)),
                ("sponsor_visibility", models.TextField(blank=True)),
                ("deliverables_completed", models.TextField(blank=True)),
                ("incidents", models.TextField(blank=True)),
                ("medical_incidents", models.TextField(blank=True)),
                ("security_incidents", models.TextField(blank=True)),
                ("delays", models.TextField(blank=True)),
                ("stadium_issues", models.TextField(blank=True)),
                ("equipment_issues", models.TextField(blank=True)),
                ("photos_metadata", models.JSONField(blank=True, default=list)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("successes", models.TextField(blank=True)),
                ("challenges", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_reports",
                        to="accounts.club",
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matchday_reports",
                        to="dashboards.match",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_matchday_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_matchday_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["club", "status"], name="club_operat_club_id_210a45_idx"
                    ),
                    models.Index(
                        fields=["match", "status"],
                        name="club_operat_match_i_b54022_idx",
                    ),
                    models.Index(
                        fields=["submitted_by", "status"],
                        name="club_operat_submitt_917636_idx",
                    ),
                    models.Index(
                        fields=["submitted_at"], name="club_operat_submitt_8cf55b_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_deleted", False)),
                        fields=("match", "club"),
                        name="unique_matchday_report_per_club_match",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="sponsorcampaign",
            index=models.Index(
                fields=["club", "status"], name="club_operat_club_id_950765_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorcampaign",
            index=models.Index(
                fields=["sponsor", "status"], name="club_operat_sponsor_bafc14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorcampaign",
            index=models.Index(
                fields=["start_date", "end_date"], name="club_operat_start_d_091db5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sponsorcampaign",
            index=models.Index(
                fields=["campaign_type"], name="club_operat_campaig_754f7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignassignment",
            index=models.Index(
                fields=["campaign", "match"], name="club_operat_campaig_c7cf69_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignassignment",
            index=models.Index(
                fields=["activation_status"], name="club_operat_activat_b8b039_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("match__isnull", False)),
                fields=("campaign", "match"),
                name="unique_campaign_match_assignment",
            ),
        ),
        migrations.AddIndex(
            model_name="ticketingofficerassignment",
            index=models.Index(
                fields=["club", "match"], name="club_operat_club_id_2d2c5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketingofficerassignment",
            index=models.Index(
                fields=["officer", "status"], name="club_operat_officer_24152c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketingofficerassignment",
            index=models.Index(
                fields=["match", "status"], name="club_operat_match_i_ca3f1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ticketingofficerassignment",
            index=models.Index(
                fields=["assignment_role"], name="club_operat_assignm_88bce9_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="ticketingofficerassignment",
            constraint=models.UniqueConstraint(
                fields=("match", "officer", "assignment_role"),
                name="unique_officer_match_role_assignment",
            ),
        ),
    ]
