# Generated by Django 5.2.14 on 2026-07-21 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("club_operations", "0002_sponsorcampaign_campaignassignment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubOperationAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CAMPAIGN_CREATED", "Campaign Created"),
                            ("CAMPAIGN_UPDATED", "Campaign Updated"),
                            ("CAMPAIGN_ARCHIVED", "Campaign Archived"),
                            ("CAMPAIGN_DELETED", "Campaign Deleted"),
                            ("CAMPAIGN_TAGGED", "Campaign Tagged"),
                            ("CAMPAIGN_REMOVED", "Campaign Removed"),
                            (
                                "CAMPAIGN_ASSIGNMENT_UPDATED",
                                "Campaign Assignment Updated",
                            ),
                            ("TASK_CREATED", "Task Created"),
                            ("TASK_UPDATED", "Task Updated"),
                            ("TASK_COMPLETED", "Task Completed"),
                            ("OFFICER_ASSIGNED", "Officer Assigned"),
                            (
                                "OFFICER_ASSIGNMENT_UPDATED",
                                "Officer Assignment Updated",
                            ),
                            ("OFFICER_REMOVED", "Officer Removed"),
                            ("REPORT_SUBMITTED", "Report Submitted"),
                            ("REPORT_UPDATED", "Report Updated"),
                            ("REPORT_APPROVED", "Report Approved"),
                            ("REPORT_REJECTED", "Report Rejected"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "target_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("target_content_type", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_operation_audit_logs",
                        to="accounts.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_operation_audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["club", "action"], name="club_operat_club_id_839bc8_idx"
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="club_operat_user_id_db50c8_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="club_operat_timesta_123880_idx"
                    ),
                ],
            },
        ),
    ]
