# Generated by Django 5.2.14 on 2026-06-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_add_missing_user_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="League",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="leagues/logos/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Union",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="unions/logos/"),
                ),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("founded_year", models.PositiveIntegerField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("season", models.CharField(help_text="e.g. 2025/26", max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competitions",
                        to="dashboards.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "name"],
                "unique_together": {("league", "slug")},
            },
        ),
        migrations.AddField(
            model_name="league",
            name="union",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leagues",
                to="dashboards.union",
            ),
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("LIVE", "Live"),
                            ("COMPLETED", "Completed"),
                            ("POSTPONED", "Postponed"),
                            ("CANCELLED", "Cancelled"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("match_date", models.DateTimeField()),
                ("venue", models.CharField(blank=True, max_length=300)),
                (
                    "round",
                    models.CharField(
                        blank=True,
                        help_text="Matchweek, round, or group stage",
                        max_length=100,
                    ),
                ),
                ("home_score", models.PositiveIntegerField(blank=True, null=True)),
                ("away_score", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "home_halftime_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "away_halftime_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("has_extra_time", models.BooleanField(default=False)),
                ("has_penalties", models.BooleanField(default=False)),
                (
                    "home_penalty_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "away_penalty_score",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="away_matches",
                        to="accounts.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="dashboards.competition",
                    ),
                ),
                (
                    "home_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="home_matches",
                        to="accounts.club",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "matches",
                "ordering": ["match_date"],
                "indexes": [
                    models.Index(
                        fields=["status", "match_date"],
                        name="dashboards__status_6048ca_idx",
                    ),
                    models.Index(
                        fields=["competition", "match_date"],
                        name="dashboards__competi_0df8d1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Standing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("played", models.PositiveIntegerField(default=0)),
                ("won", models.PositiveIntegerField(default=0)),
                ("drawn", models.PositiveIntegerField(default=0)),
                ("lost", models.PositiveIntegerField(default=0)),
                ("goals_for", models.PositiveIntegerField(default=0)),
                ("goals_against", models.PositiveIntegerField(default=0)),
                ("goal_difference", models.IntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                (
                    "form",
                    models.CharField(blank=True, help_text="e.g. WWDLW", max_length=50),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="accounts.club",
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standings",
                        to="dashboards.competition",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("competition", "club")},
            },
        ),
    ]
