# Generated by Django 5.2.14 on 2026-07-09 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_club_banner_club_logo_club_primary_color_and_more"),
        ("dashboards", "0002_union_workspace_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seasons",
                        to="dashboards.league",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-created_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="LeagueClubMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PROMOTED", "Promoted"),
                            ("RELEGATED", "Relegated"),
                            ("WITHDRAWN", "Withdrawn"),
                            ("INVITED", "Invited"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="league_memberships",
                        to="accounts.club",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_league_club_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "league",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="dashboards.league",
                    ),
                ),
                (
                    "promoted_from_league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_club_entries",
                        to="dashboards.league",
                    ),
                ),
                (
                    "relegated_to_league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="relegated_club_entries",
                        to="dashboards.league",
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_memberships",
                        to="dashboards.season",
                    ),
                ),
            ],
            options={
                "ordering": ["league__name", "season__name", "club__name"],
            },
        ),
        migrations.AddField(
            model_name="competition",
            name="season_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competitions",
                to="dashboards.season",
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(
                fields=["league", "is_active"], name="dashboards__league__3a8634_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="season",
            index=models.Index(fields=["slug"], name="dashboards__slug_44131b_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("league", "slug")},
        ),
        migrations.AddIndex(
            model_name="leagueclubmembership",
            index=models.Index(
                fields=["league", "status"], name="dashboards__league__5b3c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leagueclubmembership",
            index=models.Index(
                fields=["season", "status"], name="dashboards__season__d3aeab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leagueclubmembership",
            index=models.Index(
                fields=["club", "status"], name="dashboards__club_id_68b3a4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leagueclubmembership",
            unique_together={("league", "club", "season")},
        ),
    ]
