# Generated by Django 5.2.14 on 2026-07-11 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0003_season_leagueclubmembership_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionMatchOfficial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=30)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("CENTRE_REFEREE", "Centre Referee"),
                            ("ASSISTANT_REFEREE", "Assistant Referee"),
                            ("TMO", "Television Match Official"),
                            ("MATCH_COMMISSIONER", "Match Commissioner"),
                            ("ASSESSOR", "Assessor"),
                            ("SCORER", "Scorer / Table Official"),
                            ("OTHER", "Other"),
                        ],
                        default="CENTRE_REFEREE",
                        max_length=40,
                    ),
                ),
                ("certification_level", models.CharField(blank=True, max_length=80)),
                ("primary_sport", models.CharField(blank=True, max_length=80)),
                ("competitions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("UNAVAILABLE", "Unavailable"),
                            ("SUSPENDED", "Suspended"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=30,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_match_officials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match_officials",
                        to="dashboards.union",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="match_official_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="FixtureOfficialAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("CENTRE_REFEREE", "Centre Referee"),
                            ("ASSISTANT_REFEREE", "Assistant Referee"),
                            ("TMO", "Television Match Official"),
                            ("MATCH_COMMISSIONER", "Match Commissioner"),
                            ("ASSESSOR", "Assessor"),
                            ("SCORER", "Scorer / Table Official"),
                            ("OTHER", "Other"),
                        ],
                        default="CENTRE_REFEREE",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("ASSIGNED", "Assigned"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ASSIGNED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fixture_official_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="official_assignments",
                        to="dashboards.match",
                    ),
                ),
                (
                    "official",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="dashboards.unionmatchofficial",
                    ),
                ),
            ],
            options={
                "ordering": ["match__match_date", "role_type", "official__full_name"],
            },
        ),
        migrations.AddIndex(
            model_name="unionmatchofficial",
            index=models.Index(
                fields=["union", "status"], name="dashboards__union_i_f1e5c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unionmatchofficial",
            index=models.Index(
                fields=["union", "role_type"], name="dashboards__union_i_d39bfe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unionmatchofficial",
            index=models.Index(fields=["email"], name="dashboards__email_3ce545_idx"),
        ),
        migrations.AddConstraint(
            model_name="unionmatchofficial",
            constraint=models.UniqueConstraint(
                condition=models.Q(("email", ""), _negated=True),
                fields=("union", "email"),
                name="unique_union_match_official_email",
            ),
        ),
        migrations.AddIndex(
            model_name="fixtureofficialassignment",
            index=models.Index(
                fields=["match", "status"], name="dashboards__match_i_2928d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fixtureofficialassignment",
            index=models.Index(
                fields=["official", "status"], name="dashboards__officia_7e4fd0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fixtureofficialassignment",
            unique_together={("match", "official", "role_type")},
        ),
    ]
