# Generated by Django 5.2.14 on 2026-07-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0004_unionmatchofficial_fixtureofficialassignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fixtureofficialassignment",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("CENTRE_REFEREE", "Centre Referee"),
                    ("ASSISTANT_REFEREE", "Assistant Referee"),
                    ("TMO", "Television Match Official"),
                    ("CITING_COMMISSIONER", "Citing Commissioner"),
                    ("SUBSTITUTION_CONTROLLER", "Substitution Controller"),
                    ("TECHNICAL_ZONE_OFFICIAL", "Technical Zone Official"),
                    ("SCOREBOARD_OPERATOR", "Scoreboard Operator"),
                    ("FOURTH_OFFICIAL", "Fourth Official"),
                    ("VAR", "Video Assistant Referee"),
                    ("AVAR", "Assistant Video Assistant Referee"),
                    ("MATCH_COORDINATOR", "Match Coordinator"),
                    ("CREW_CHIEF", "Crew Chief"),
                    ("UMPIRE", "Umpire"),
                    ("TABLE_OFFICIAL", "Table Official"),
                    ("ASSISTANT_SCORER", "Assistant Scorer"),
                    ("TIMER", "Timer"),
                    ("SHOT_CLOCK_OPERATOR", "Shot Clock Operator"),
                    ("MATCH_COMMISSIONER", "Match Commissioner"),
                    ("ASSESSOR", "Referee Assessor"),
                    ("SCORER", "Scorer"),
                    ("TIMEKEEPER", "Timekeeper"),
                    ("OTHER", "Other Match Official"),
                ],
                default="CENTRE_REFEREE",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="unionmatchofficial",
            name="primary_sport",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RUGBY", "Rugby"),
                    ("FOOTBALL", "Football"),
                    ("BASKETBALL", "Basketball"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unionmatchofficial",
            name="role_type",
            field=models.CharField(
                choices=[
                    ("CENTRE_REFEREE", "Centre Referee"),
                    ("ASSISTANT_REFEREE", "Assistant Referee"),
                    ("TMO", "Television Match Official"),
                    ("CITING_COMMISSIONER", "Citing Commissioner"),
                    ("SUBSTITUTION_CONTROLLER", "Substitution Controller"),
                    ("TECHNICAL_ZONE_OFFICIAL", "Technical Zone Official"),
                    ("SCOREBOARD_OPERATOR", "Scoreboard Operator"),
                    ("FOURTH_OFFICIAL", "Fourth Official"),
                    ("VAR", "Video Assistant Referee"),
                    ("AVAR", "Assistant Video Assistant Referee"),
                    ("MATCH_COORDINATOR", "Match Coordinator"),
                    ("CREW_CHIEF", "Crew Chief"),
                    ("UMPIRE", "Umpire"),
                    ("TABLE_OFFICIAL", "Table Official"),
                    ("ASSISTANT_SCORER", "Assistant Scorer"),
                    ("TIMER", "Timer"),
                    ("SHOT_CLOCK_OPERATOR", "Shot Clock Operator"),
                    ("MATCH_COMMISSIONER", "Match Commissioner"),
                    ("ASSESSOR", "Referee Assessor"),
                    ("SCORER", "Scorer"),
                    ("TIMEKEEPER", "Timekeeper"),
                    ("OTHER", "Other Match Official"),
                ],
                default="CENTRE_REFEREE",
                max_length=40,
            ),
        ),
    ]
