# Generated by Django 5.2.14 on 2026-07-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0007_league_admin_scope_and_official_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unionworkspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Workspace Owner"),
                    ("UNION_ADMIN", "Union Admin"),
                    ("COMPETITIONS_MANAGER", "Competitions Manager"),
                    ("REGISTRAR", "Player Registrar"),
                    ("REFEREE_MANAGER", "Referee Manager"),
                    ("MATCH_OFFICIAL", "Match Official"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("COMMUNICATIONS_OFFICER", "Communications Officer"),
                    ("TICKETING_OFFICER", "Ticketing Officer"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=40,
            ),
        ),
    ]
