# Generated by Django 5.2.14 on 2026-07-20 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0009_union_operational_contracts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionworkspacemembership",
            name="scope_restrictions",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Optional resource scope restrictions, keyed by resource type. An empty object grants the workspace-wide role template.",
            ),
        ),
        migrations.AlterField(
            model_name="unionworkspacemembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "Workspace Owner"),
                    ("UNION_ADMIN", "Union Admin"),
                    ("COMPETITIONS_MANAGER", "Competitions Manager"),
                    ("REGISTRAR", "Player Registrar"),
                    ("REFEREE_MANAGER", "Referee Manager"),
                    ("MATCH_OFFICIAL", "Match Official"),
                    ("FINANCE_OFFICER", "Finance Officer"),
                    ("COMMUNICATIONS_OFFICER", "Communications Officer"),
                    ("SPONSORSHIP_OFFICER", "Sponsorship Officer"),
                    ("NATIONAL_TEAM_MANAGER", "National Team Manager"),
                    ("TECHNICAL_ADMINISTRATOR", "Technical Administrator"),
                    ("CUSTOM_USER", "Custom User"),
                    ("TICKETING_OFFICER", "Ticketing Officer"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="UnionApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.PositiveBigIntegerField()),
                ("action", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_approvals_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_approvals_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approvals",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status", "created_at"],
                        name="dash_approval_ws_status_idx",
                    ),
                    models.Index(
                        fields=["workspace", "subject_type", "subject_id"],
                        name="dash_approval_subject_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnionAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=120)),
                ("target_type", models.CharField(blank=True, max_length=80)),
                ("target_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "created_at"],
                        name="dash_audit_ws_created_idx",
                    ),
                    models.Index(
                        fields=["workspace", "action"], name="dash_audit_ws_action_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="dash_audit_target_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UnionDocumentReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.PositiveBigIntegerField()),
                ("document_type", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=200)),
                ("file_url", models.URLField(max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_union_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="document_references",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "subject_type", "subject_id"],
                        name="dash_document_subject_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UnionReviewComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject_type", models.CharField(max_length=80)),
                ("subject_id", models.PositiveBigIntegerField()),
                ("body", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_review_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_comments",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "subject_type", "subject_id"],
                        name="dash_comment_subject_idx",
                    )
                ],
            },
        ),
    ]
