# Generated by Django 5.2.14 on 2026-07-20 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def backfill_competition_identities_and_editions(apps, schema_editor):
    """Add Phase 2 records without altering existing competition history."""

    Competition = apps.get_model("dashboards", "Competition")
    CompetitionEdition = apps.get_model("dashboards", "CompetitionEdition")
    CompetitionIdentity = apps.get_model("dashboards", "CompetitionIdentity")

    identities = {}
    occupied_slugs = set(CompetitionIdentity.objects.values_list("union_id", "slug"))

    for competition in Competition.objects.select_related("league").order_by(
        "league_id", "name", "id"
    ):
        key = (competition.league_id, competition.name)
        identity = identities.get(key)
        if identity is None:
            base_slug = (
                slugify(f"{competition.league.slug}-{competition.name}")[:190]
                or f"competition-{competition.id}"
            )
            slug = base_slug
            suffix = 2
            while (competition.league.union_id, slug) in occupied_slugs:
                slug = f"{base_slug[:190 - len(str(suffix))]}-{suffix}"
                suffix += 1
            identity = CompetitionIdentity.objects.create(
                union_id=competition.league.union_id,
                primary_league_id=competition.league_id,
                name=competition.name,
                slug=slug,
                is_active=competition.is_active,
            )
            identities[key] = identity
            occupied_slugs.add((competition.league.union_id, slug))

        if (
            competition.season_record_id
            and CompetitionEdition.objects.filter(
                identity_id=identity.id,
                season_id=competition.season_record_id,
            ).exists()
        ):
            duplicate_slug = f"{slug[:180]}-legacy-{competition.id}"
            identity = CompetitionIdentity.objects.create(
                union_id=competition.league.union_id,
                primary_league_id=competition.league_id,
                name=competition.name,
                slug=duplicate_slug,
                is_active=competition.is_active,
            )

        CompetitionEdition.objects.get_or_create(
            competition_id=competition.id,
            defaults={
                "identity_id": identity.id,
                "season_id": competition.season_record_id,
                "status": "ACTIVE" if competition.is_active else "ARCHIVED",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0010_unionworkspacemembership_scope_restrictions_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompetitionIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200)),
                ("sport", models.CharField(blank=True, max_length=80)),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("LEAGUE", "League"),
                            ("KNOCKOUT", "Knockout"),
                            ("GROUP_AND_KNOCKOUT", "Group and knockout"),
                            ("TOURNAMENT", "Tournament"),
                            ("SERIES", "Short-format series"),
                            ("COMMUNITY", "Community competition"),
                        ],
                        default="LEAGUE",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("branding", models.JSONField(blank=True, default=dict)),
                ("default_format", models.JSONField(blank=True, default=dict)),
                (
                    "default_eligibility_rules",
                    models.JSONField(blank=True, default=dict),
                ),
                ("tier", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "higher_competition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lower_competitions",
                        to="dashboards.competitionidentity",
                    ),
                ),
                (
                    "primary_league",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_identities",
                        to="dashboards.league",
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_identities",
                        to="dashboards.union",
                    ),
                ),
            ],
            options={
                "ordering": ["union__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="CompetitionEdition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REGISTRATION_OPEN", "Registration open"),
                            ("REGISTRATION_CLOSED", "Registration closed"),
                            ("ENTRIES_UNDER_REVIEW", "Entries under review"),
                            ("SCHEDULING", "Scheduling"),
                            ("READY_FOR_PUBLICATION", "Ready for publication"),
                            ("PUBLISHED", "Published"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                            ("ARCHIVED", "Archived"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=30,
                    ),
                ),
                ("registration_opens_at", models.DateTimeField(blank=True, null=True)),
                ("registration_closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entry_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("currency", models.CharField(default="UGX", max_length=3)),
                ("rules", models.JSONField(blank=True, default=dict)),
                ("structure", models.JSONField(blank=True, default=dict)),
                ("eligibility_rules", models.JSONField(blank=True, default=dict)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_edition",
                        to="dashboards.competition",
                    ),
                ),
                (
                    "copied_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="copied_editions",
                        to="dashboards.competitionedition",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_competition_editions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competition_editions",
                        to="dashboards.season",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="editions",
                        to="dashboards.competitionidentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-season__start_date", "-created_at", "identity__name"],
            },
        ),
        migrations.AddIndex(
            model_name="competitionidentity",
            index=models.Index(
                fields=["union", "is_active"], name="dashboards__union_i_cf4c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competitionidentity",
            index=models.Index(
                fields=["primary_league", "is_active"],
                name="dashboards__primary_4d3c99_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionidentity",
            constraint=models.UniqueConstraint(
                fields=("union", "slug"), name="unique_union_competition_identity_slug"
            ),
        ),
        migrations.AddIndex(
            model_name="competitionedition",
            index=models.Index(
                fields=["identity", "status"], name="dashboards__identit_d7fb7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competitionedition",
            index=models.Index(
                fields=["season", "status"], name="dashboards__season__367104_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="competitionedition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("season__isnull", False)),
                fields=("identity", "season"),
                name="unique_identity_competition_edition_season",
            ),
        ),
        migrations.RunPython(
            backfill_competition_identities_and_editions,
            migrations.RunPython.noop,
        ),
    ]
