# Generated by Django 5.2.14 on 2026-07-20 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("dashboards", "0011_competitionidentity_competitionedition_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("union_player_number", models.CharField(max_length=80)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                ("identity_reference", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROVISIONAL", "Provisional"),
                            ("APPROVED", "Approved"),
                            ("SUSPENDED", "Suspended"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PROVISIONAL",
                        max_length=20,
                    ),
                ),
                ("identity_verified_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "identity_verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_union_players",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "union",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="players",
                        to="dashboards.union",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_player_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name", "id"],
            },
        ),
        migrations.AddField(
            model_name="nationalteammember",
            name="player",
            field=models.ForeignKey(
                blank=True,
                help_text="Required for player selections from the approved Union player pool.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="national_team_assignments",
                to="dashboards.unionplayer",
            ),
        ),
        migrations.CreateModel(
            name="UnionPlayerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("TRANSFERRED", "Transferred"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_union_player_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="union_player_registration_history",
                        to="accounts.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_registration_history",
                        to="dashboards.unionplayer",
                    ),
                ),
                (
                    "source_registration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_registration_history",
                        to="teams.playerregistration",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_player_registrations",
                        to="teams.team",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_registrations",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UnionPlayerTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SOURCE_CLUB_RESPONSE", "Source Club response"),
                            ("PLAYER_CONSENT", "Player consent"),
                            ("UNDER_REVIEW", "Under review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("effective_on", models.DateField()),
                (
                    "source_club_response_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("player_consented_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_union_player_transfers",
                        to="accounts.club",
                    ),
                ),
                (
                    "destination_team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incoming_union_player_transfers",
                        to="teams.team",
                    ),
                ),
                (
                    "initiated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="initiated_union_player_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "legacy_transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_transfer_workflow",
                        to="teams.playertransfer",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers",
                        to="dashboards.unionplayer",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_union_player_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outgoing_transfers",
                        to="dashboards.unionplayerregistration",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_transfers",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ClubAffiliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("APPLICATION_SUBMITTED", "Application submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("CHANGES_REQUESTED", "Changes requested"),
                            ("PROVISIONAL", "Provisional"),
                            ("ACTIVE", "Active"),
                            ("RENEWAL_DUE", "Renewal due"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="APPLICATION_SUBMITTED",
                        max_length=30,
                    ),
                ),
                ("expires_on", models.DateField(blank=True, null=True)),
                (
                    "compliance_status",
                    models.CharField(default="PENDING", max_length=50),
                ),
                ("compliance_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="union_affiliations",
                        to="accounts.club",
                    ),
                ),
                (
                    "liaison",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="club_affiliations_as_liaison",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="club_affiliations",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="dashboards__workspa_3fdf59_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "club"),
                        name="unique_workspace_club_affiliation",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="unionplayer",
            index=models.Index(
                fields=["union", "status"], name="dashboards__union_i_9f64f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unionplayer",
            index=models.Index(
                fields=["union", "last_name", "first_name"],
                name="dashboards__union_i_5bfe97_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="unionplayer",
            constraint=models.UniqueConstraint(
                fields=("union", "union_player_number"),
                name="unique_union_player_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="unionplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("identity_reference", ""), _negated=True),
                fields=("union", "identity_reference"),
                name="unique_union_player_identity_reference",
            ),
        ),
        migrations.AddIndex(
            model_name="unionplayerregistration",
            index=models.Index(
                fields=["workspace", "club", "status"],
                name="dashboards__workspa_35ef7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="unionplayerregistration",
            index=models.Index(
                fields=["player", "status"], name="dashboards__player__eaa77c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unionplayerregistration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "player"),
                name="unique_active_workspace_player_registration",
            ),
        ),
        migrations.AddIndex(
            model_name="unionplayertransfer",
            index=models.Index(
                fields=["workspace", "status"], name="dashboards__workspa_da260f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="unionplayertransfer",
            index=models.Index(
                fields=["player", "status"], name="dashboards__player__8ca336_idx"
            ),
        ),
    ]
