# Generated by Django 5.2.14 on 2026-07-20 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0012_unionplayer_nationalteammember_player_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnionPlayerNumberSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("next_value", models.PositiveBigIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "union",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_number_sequence",
                        to="dashboards.union",
                    ),
                ),
            ],
        ),
    ]
