# Generated by Django 5.2.14 on 2026-07-20 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("dashboards", "0013_unionplayernumbersequence"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayerregistration",
            name="change_request_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unionplayerregistration",
            name="decision_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unionplayerregistration",
            name="predecessor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successor_registrations",
                to="dashboards.unionplayerregistration",
            ),
        ),
        migrations.AddField(
            model_name="unionplayerregistration",
            name="registration_type",
            field=models.CharField(default="FIRST_REGISTRATION", max_length=40),
        ),
        migrations.AddField(
            model_name="unionplayerregistration",
            name="season",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="union_player_registrations",
                to="dashboards.season",
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="change_request_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="fee_status",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="loan_end_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="player_consent_method",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="source_club_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="transfer_type",
            field=models.CharField(default="PERMANENT", max_length=30),
        ),
        migrations.AlterField(
            model_name="unionplayer",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROVISIONAL", "Provisional"),
                    ("PENDING_VERIFICATION", "Pending verification"),
                    ("APPROVED", "Approved"),
                    ("SUSPENDED", "Suspended"),
                    ("REJECTED", "Rejected"),
                    ("ARCHIVED", "Archived"),
                ],
                default="PROVISIONAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unionplayerregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("APPROVED", "Approved"),
                    ("ACTIVE", "Active"),
                    ("TRANSFERRED", "Transferred"),
                    ("EXPIRED", "Expired"),
                    ("SUSPENDED", "Suspended"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="unionplayertransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PLAYER_CONSENT_REQUIRED", "Player consent required"),
                    ("SOURCE_CLUB_RESPONSE_REQUIRED", "Source Club response required"),
                    ("UNDER_AUTOMATIC_REVIEW", "Under automatic review"),
                    ("UNDER_UNION_REVIEW", "Under Union review"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                ],
                default="DRAFT",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="UnionPlayerCompetitionEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ELIGIBLE", "Eligible"),
                            ("INELIGIBLE", "Ineligible"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("eligible_from", models.DateField(blank=True, null=True)),
                ("eligible_until", models.DateField(blank=True, null=True)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("restriction_reason", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("decision_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="union_competition_eligibilities",
                        to="accounts.club",
                    ),
                ),
                (
                    "competition_edition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_eligibilities",
                        to="dashboards.competitionedition",
                    ),
                ),
                (
                    "competition_identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_eligibilities",
                        to="dashboards.competitionidentity",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_eligibilities",
                        to="dashboards.unionplayer",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_eligibilities",
                        to="dashboards.unionplayerregistration",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_competition_eligibilities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="player_eligibilities",
                        to="dashboards.season",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="union_competition_eligibilities",
                        to="teams.team",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competition_eligibilities",
                        to="dashboards.unionworkspace",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["workspace", "status"],
                        name="dashboards__workspa_2b3ce8_idx",
                    ),
                    models.Index(
                        fields=["competition_edition", "status"],
                        name="dashboards__competi_7c6f93_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "ELIGIBLE")),
                        fields=("player", "competition_edition"),
                        name="unique_eligible_player_edition",
                    )
                ],
            },
        ),
    ]
