# Generated by Django 5.2.14 on 2026-07-20 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("dashboards", "0014_unionplayerregistration_change_request_reason_and_more"),
        ("teams", "0002_playerregistration_assigned_reviewer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayercompetitioneligibility",
            name="source_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="competition_eligibility_history",
                to="teams.playerregistration",
            ),
        ),
        migrations.AddConstraint(
            model_name="unionplayercompetitioneligibility",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_submission__isnull", False)),
                fields=("source_submission", "competition_edition"),
                name="unique_submission_competition_edition",
            ),
        ),
    ]
