# Generated by Django 5.2.14 on 2026-07-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboards",
            "0015_unionplayercompetitioneligibility_source_submission_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayertransfer",
            name="automatic_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="cancellation_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_union_player_transfers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="player_consent_recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recorded_player_transfer_consents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="player_consent_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("CONSENTED", "Consented"),
                    ("DECLINED", "Declined"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="source_club_responded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_club_transfer_responses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="source_club_response_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACKNOWLEDGED", "Acknowledged"),
                    ("OBJECTED", "Objected"),
                ],
                default="PENDING",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="submission_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
