# Generated by Django 5.2.14 on 2026-07-20 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("dashboards", "0016_unionplayertransfer_submission_lifecycle"),
        ("teams", "0002_playerregistration_assigned_reviewer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayercompetitioneligibility",
            name="source_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destination_competition_eligibilities",
                to="dashboards.unionplayertransfer",
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="destination_registration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="completed_transfer",
                to="dashboards.unionplayerregistration",
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="last_resubmitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="unionplayercompetitioneligibility",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_transfer__isnull", False)),
                fields=("source_transfer", "competition_edition"),
                name="unique_transfer_competition_edition",
            ),
        ),
    ]
