# Generated by Django 5.2.14 on 2026-07-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0017_union_transfer_decision_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayertransfer",
            name="activated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="activation_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="source_registration_original_effective_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="unionplayertransfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("PLAYER_CONSENT_REQUIRED", "Player consent required"),
                    ("SOURCE_CLUB_RESPONSE_REQUIRED", "Source Club response required"),
                    ("UNDER_AUTOMATIC_REVIEW", "Under automatic review"),
                    ("UNDER_UNION_REVIEW", "Under Union review"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                    ("LOAN_ACTIVE", "Loan active"),
                    ("COMPLETED", "Completed"),
                    ("EXPIRED", "Expired"),
                ],
                default="DRAFT",
                max_length=40,
            ),
        ),
    ]
