# Generated by Django 5.2.14 on 2026-07-20 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_merge_notification_migration_branches"),
        ("dashboards", "0018_union_transfer_activation"),
        ("teams", "0002_playerregistration_assigned_reviewer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="unionplayercompetitioneligibility",
            name="source_loan_return",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="return_competition_eligibilities",
                to="dashboards.unionplayertransfer",
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="return_plan",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="return_registration",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="completed_loan_return",
                to="dashboards.unionplayerregistration",
            ),
        ),
        migrations.AddField(
            model_name="unionplayertransfer",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="unionplayercompetitioneligibility",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_loan_return__isnull", False)),
                fields=("source_loan_return", "competition_edition"),
                name="unique_loan_return_competition_edition",
            ),
        ),
    ]
