# Generated by Django 5.2.14 on 2026-07-15 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0009_club_banner_club_logo_club_primary_color_and_more"),
        ("dashboards", "0008_add_union_ticketing_officer_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("FIRST_TEAM", "First Team"),
                            ("RESERVE", "Reserve Team"),
                            ("YOUTH", "Youth Team"),
                            ("U20", "U-20"),
                            ("U17", "U-17"),
                            ("U15", "U-15"),
                            ("WOMEN", "Women's Team"),
                            ("OTHER", "Other"),
                        ],
                        default="FIRST_TEAM",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="teams/logos/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="accounts.club",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name", "team_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("HEAD_COACH", "Head Coach"),
                            ("ASSISTANT_COACH", "Assistant Coach"),
                            ("GOALKEEPING_COACH", "Goalkeeping Coach"),
                            ("FITNESS_COACH", "Fitness Coach"),
                            ("MEDICAL_OFFICER", "Medical Officer"),
                            ("PHYSIOTHERAPIST", "Physiotherapist"),
                            ("TEAM_MANAGER", "Team Manager"),
                            ("CHAIRMAN", "Chairman"),
                            ("DIRECTOR_OF_FOOTBALL", "Director of Football"),
                            ("SCOUT", "Scout"),
                            ("ANALYST", "Performance Analyst"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "custom_role",
                    models.CharField(
                        blank=True, help_text="Use if role is OTHER", max_length=100
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time"),
                            ("PART_TIME", "Part-Time"),
                            ("CONTRACT", "Contract"),
                            ("VOLUNTEER", "Volunteer"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("qualification", models.TextField(blank=True)),
                (
                    "experience_years",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="accounts.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name", "team__name", "role", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("season", models.CharField(help_text="e.g., 2025/26", max_length=50)),
                ("member_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_squads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squads",
                        to="dashboards.competition",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_squads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squads",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlayerRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Unique registration number assigned by club",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        help_text="Primary playing position", max_length=50
                    ),
                ),
                ("secondary_positions", models.JSONField(blank=True, default=list)),
                (
                    "player_type",
                    models.CharField(
                        choices=[
                            ("PROFESSIONAL", "Professional"),
                            ("SEMI_PRO", "Semi-Professional"),
                            ("AMATEUR", "Amateur"),
                            ("YOUTH", "Youth"),
                            ("LOAN", "Loan Player"),
                        ],
                        default="PROFESSIONAL",
                        max_length=20,
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("height_cm", models.PositiveIntegerField(blank=True, null=True)),
                ("weight_kg", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "preferred_foot",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LEFT", "Left"),
                            ("RIGHT", "Right"),
                            ("BOTH", "Both"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("registered_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "transfer_window",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Summer 2025, Winter 2025",
                        max_length=50,
                    ),
                ),
                ("previous_club", models.CharField(blank=True, max_length=200)),
                ("contract_until", models.DateField(blank=True, null=True)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registrations",
                        to="accounts.club",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to user account if player has one",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="player_registrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_registrations",
                        to="teams.team",
                    ),
                ),
            ],
            options={
                "ordering": ["club__name", "team__name", "registration_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.CharField(
                        help_text="Unique transfer reference number",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "transfer_type",
                    models.CharField(
                        choices=[
                            ("PERMANENT", "Permanent Transfer"),
                            ("LOAN", "Loan"),
                            ("FREE_TRANSFER", "Free Transfer"),
                            ("END_OF_LOAN", "End of Loan"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "transfer_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Transfer fee in case of permanent transfer",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("transfer_date", models.DateField()),
                ("contract_until", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outgoing_transfers",
                        to="accounts.club",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="teams.playerregistration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requested_transfers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incoming_transfers",
                        to="accounts.club",
                    ),
                ),
            ],
            options={
                "ordering": ["-transfer_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["player", "status"],
                        name="teams_playe_player__5d0921_idx",
                    ),
                    models.Index(
                        fields=["from_club", "to_club"],
                        name="teams_playe_from_cl_e65199_idx",
                    ),
                    models.Index(
                        fields=["transfer_date"], name="teams_playe_transfe_0bc4d3_idx"
                    ),
                    models.Index(
                        fields=["status"], name="teams_playe_status_08a73f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SquadMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jersey_number", models.PositiveIntegerField(blank=True, null=True)),
                ("position", models.CharField(max_length=50)),
                ("is_captain", models.BooleanField(default=False)),
                ("is_vice_captain", models.BooleanField(default=False)),
                ("joined_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_memberships",
                        to="teams.playerregistration",
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="teams.squad",
                    ),
                ),
            ],
            options={
                "ordering": ["jersey_number", "player__last_name"],
                "indexes": [
                    models.Index(
                        fields=["squad", "player"],
                        name="teams_squad_squad_i_679555_idx",
                    )
                ],
                "unique_together": {("squad", "player")},
            },
        ),
        migrations.CreateModel(
            name="SquadSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submission_number",
                    models.CharField(
                        help_text="Unique submission reference",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("AMENDED", "Amended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "iteration",
                    models.PositiveIntegerField(default=1, help_text="Version number"),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "previous_submission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="amendments",
                        to="teams.squadsubmission",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_squad_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "squad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="teams.squad",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="squad_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["squad", "status"],
                        name="teams_squad_squad_i_8e5fa2_idx",
                    ),
                    models.Index(
                        fields=["status", "-submitted_at"],
                        name="teams_squad_status_9f6706_idx",
                    ),
                    models.Index(
                        fields=["submission_number"],
                        name="teams_squad_submiss_c4c3d8_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["club", "is_active"], name="teams_team_club_id_1ea644_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_type"], name="teams_team_team_ty_40b61e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="team",
            unique_together={("club", "name")},
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["club", "role"], name="teams_staff_club_id_724c09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(
                fields=["team", "role"], name="teams_staff_team_id_e023cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffmember",
            index=models.Index(fields=["user"], name="teams_staff_user_id_3bbd65_idx"),
        ),
        migrations.AddIndex(
            model_name="squad",
            index=models.Index(
                fields=["team", "competition", "season"],
                name="teams_squad_team_id_45d829_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="squad",
            index=models.Index(
                fields=["status", "-submitted_at"], name="teams_squad_status_c460d0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="squad",
            unique_together={("team", "competition", "season")},
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["club", "status"], name="teams_playe_club_id_bd152b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["team", "status"], name="teams_playe_team_id_6292f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(
                fields=["registration_number"], name="teams_playe_registr_b643af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playerregistration",
            index=models.Index(fields=["user"], name="teams_playe_user_id_e366e8_idx"),
        ),
    ]
