# Generated by Django 5.2.14 on 2026-07-20 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboards", "0014_unionplayerregistration_change_request_reason_and_more"),
        ("teams", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="playerregistration",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_player_registration_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="automatic_validation",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="change_request_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="club_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="last_resubmitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="registration_type",
            field=models.CharField(
                choices=[
                    ("FIRST_REGISTRATION", "First registration"),
                    ("SEASON_RENEWAL", "Season renewal"),
                    ("COMPETITION_REGISTRATION", "Competition registration"),
                    ("DUAL_REGISTRATION", "Dual registration"),
                    ("FREE_AGENT_REGISTRATION", "Free agent registration"),
                ],
                default="FIRST_REGISTRATION",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="requested_competition_editions",
            field=models.ManyToManyField(
                blank=True,
                related_name="requested_player_submissions",
                to="dashboards.competitionedition",
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="season_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_player_submissions",
                to="dashboards.season",
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="submission_revision",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("LEGACY", "Legacy roster record"),
                    ("DRAFT", "Draft"),
                    ("SUBMITTED", "Submitted"),
                    ("UNDER_AUTOMATIC_REVIEW", "Under automatic review"),
                    ("UNDER_UNION_REVIEW", "Under Union review"),
                    ("CHANGES_REQUESTED", "Changes requested"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("WITHDRAWN", "Withdrawn"),
                    ("EXPIRED", "Expired"),
                ],
                default="LEGACY",
                help_text="Submission workflow state; legacy roster status remains in status.",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="submitted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_player_registrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="supporting_documents",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="union_decision_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="union_player",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_submissions",
                to="dashboards.unionplayer",
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="union_workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="club_player_submissions",
                to="dashboards.unionworkspace",
            ),
        ),
        migrations.AddField(
            model_name="playerregistration",
            name="withdrawal_reason",
            field=models.TextField(blank=True),
        ),
    ]
